/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.Conexion;
import Modelo.Material;
import Negocio.MaterialConsultas;
import Negocio.TLogin;
import java.sql.*;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esteban
 */
public class GUI_Materiales extends javax.swing.JFrame {

    TLogin tLogin = new TLogin();
    
    public GUI_Materiales(){
        initComponents();
        muestraFecha();
        llenarTabla();
        jLabel3.setText(tLogin.getUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir_Fun = new javax.swing.JLabel();
        btnAtras_Fun = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblDate = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        PanelMenuMateriales = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        PanelIngresarMateriales = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnLimpiarMat = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        txtNombreMat = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtStockMaterial = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btnInsertarMat = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        PanelEditarMat = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        txtIdMaterial = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        btnEditarMat = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        btnLimpiarEditMat = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        btnBuscarMat = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtNombreMatEdit = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtStockMaterialEdit = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        PanelEliminarMaterial = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        txtMaterialCodElim = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        btnEliminarMaterial = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        btnLimpiarElimMat = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        PanelListarMateriales = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadoMateriales = new javax.swing.JTable();
        PanelMaterialEspecifico = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        txtRutFun_Proyecto = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        btnBuscarMatEsp = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMaterialEspecifico = new javax.swing.JTable();
        jLabel51 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBuscarMaterial = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnIngresarMaterial = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnEditarMaterial = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnPEliminarMaterial = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnListarMateriales = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenido");

        btnSalir_Fun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CERRAR_MINI_ICON.png"))); // NOI18N
        btnSalir_Fun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalir_FunMouseClicked(evt);
            }
        });

        btnAtras_Fun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ATRAS_MINI_ICON.png"))); // NOI18N
        btnAtras_Fun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtras_FunMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("USER");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/USER_MINI_ICON_MAINMENU.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSTRUCTORA VIALIS");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CALENDARIO_MINI_ICON_MAINMENU.png"))); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("jLabel6");

        jPanel9.setBackground(new java.awt.Color(102, 102, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel9.setLayout(new java.awt.CardLayout());

        PanelMenuMateriales.setBackground(new java.awt.Color(102, 102, 255));
        PanelMenuMateriales.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("¡Bienvenido al menú de Materiales!");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Utiliza diversas herramientas para el control y gestión de materiales Vialis");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MenuMateriales.png"))); // NOI18N

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Funciones disponibles: ");

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("1.- Inserción de Materiales");

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("2.- Edición de Materiales");

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("4.- Listar Materiales");

        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("3.- Eliminar Material");

        jLabel59.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("5.- Buscar Material específico");

        javax.swing.GroupLayout PanelMenuMaterialesLayout = new javax.swing.GroupLayout(PanelMenuMateriales);
        PanelMenuMateriales.setLayout(PanelMenuMaterialesLayout);
        PanelMenuMaterialesLayout.setHorizontalGroup(
            PanelMenuMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuMaterialesLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(PanelMenuMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(PanelMenuMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(PanelMenuMaterialesLayout.createSequentialGroup()
                            .addGroup(PanelMenuMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel54)
                                .addComponent(jLabel55)
                                .addComponent(jLabel56)
                                .addComponent(jLabel57)
                                .addComponent(jLabel58)
                                .addComponent(jLabel59))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11))
                        .addComponent(jLabel52)))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        PanelMenuMaterialesLayout.setVerticalGroup(
            PanelMenuMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuMaterialesLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel52)
                .addGroup(PanelMenuMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuMaterialesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel59))
                    .addGroup(PanelMenuMaterialesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel11)))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        jPanel9.add(PanelMenuMateriales, "card7");

        PanelIngresarMateriales.setBackground(new java.awt.Color(102, 102, 255));
        PanelIngresarMateriales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelIngresarMateriales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Registro de Funcionario");
        PanelIngresarMateriales.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nombre:");
        PanelIngresarMateriales.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Stock:");
        PanelIngresarMateriales.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        btnLimpiarMat.setBackground(new java.awt.Color(204, 51, 0));
        btnLimpiarMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarMatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarMatMouseExited(evt);
            }
        });
        btnLimpiarMat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("LIMPIAR");
        btnLimpiarMat.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 13, -1, -1));

        PanelIngresarMateriales.add(btnLimpiarMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 140, 50));

        txtNombreMat.setBackground(new java.awt.Color(102, 102, 255));
        txtNombreMat.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreMat.setText("Ingrese nombre aquí...");
        txtNombreMat.setBorder(null);
        PanelIngresarMateriales.add(txtNombreMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 192, -1));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        PanelIngresarMateriales.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 192, -1));

        txtStockMaterial.setBackground(new java.awt.Color(102, 102, 255));
        txtStockMaterial.setForeground(new java.awt.Color(255, 255, 255));
        txtStockMaterial.setText("Ingrese stock...");
        txtStockMaterial.setBorder(null);
        PanelIngresarMateriales.add(txtStockMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 210, -1));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        PanelIngresarMateriales.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 210, -1));

        btnInsertarMat.setBackground(new java.awt.Color(0, 153, 153));
        btnInsertarMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarMatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInsertarMatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInsertarMatMouseExited(evt);
            }
        });
        btnInsertarMat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("INGRESAR");
        btnInsertarMat.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 13, -1, -1));

        PanelIngresarMateriales.add(btnInsertarMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 150, 50));

        jPanel9.add(PanelIngresarMateriales, "card2");

        PanelEditarMat.setBackground(new java.awt.Color(102, 102, 255));
        PanelEditarMat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelEditarMat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Edición de Material");
        PanelEditarMat.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Ingrese ID de Material: ");

        txtIdMaterial.setBackground(new java.awt.Color(102, 102, 255));
        txtIdMaterial.setForeground(new java.awt.Color(255, 255, 255));
        txtIdMaterial.setText("Ingrese código aquí...");
        txtIdMaterial.setBorder(null);

        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));

        btnEditarMat.setBackground(new java.awt.Color(0, 153, 153));
        btnEditarMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMatMouseExited(evt);
            }
        });
        btnEditarMat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("EDITAR");
        btnEditarMat.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 13, -1, -1));

        btnLimpiarEditMat.setBackground(new java.awt.Color(204, 51, 0));
        btnLimpiarEditMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarEditMatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarEditMatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarEditMatMouseExited(evt);
            }
        });
        btnLimpiarEditMat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("LIMPIAR");
        btnLimpiarEditMat.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jSeparator12.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnBuscarMat.setBackground(new java.awt.Color(255, 204, 51));
        btnBuscarMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMatMouseExited(evt);
            }
        });
        btnBuscarMat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("BUSCAR");
        btnBuscarMat.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(txtIdMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnBuscarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiarEditMat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(5, 5, 5)
                        .addComponent(txtIdMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnLimpiarEditMat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarMat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(btnEditarMat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PanelEditarMat.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 740, 100));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nombre:");
        PanelEditarMat.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Stock:");
        PanelEditarMat.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        txtNombreMatEdit.setBackground(new java.awt.Color(102, 102, 255));
        txtNombreMatEdit.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreMatEdit.setText("Ingrese nombre aquí...");
        txtNombreMatEdit.setBorder(null);
        PanelEditarMat.add(txtNombreMatEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 192, -1));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        PanelEditarMat.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 192, -1));

        txtStockMaterialEdit.setBackground(new java.awt.Color(102, 102, 255));
        txtStockMaterialEdit.setForeground(new java.awt.Color(255, 255, 255));
        txtStockMaterialEdit.setText("Ingrese stock...");
        txtStockMaterialEdit.setBorder(null);
        PanelEditarMat.add(txtStockMaterialEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 210, -1));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        PanelEditarMat.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 210, -1));

        jPanel9.add(PanelEditarMat, "card2");

        PanelEliminarMaterial.setBackground(new java.awt.Color(102, 102, 255));
        PanelEliminarMaterial.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBackground(new java.awt.Color(102, 102, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Ingrese Código de Material");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtMaterialCodElim.setBackground(new java.awt.Color(102, 102, 255));
        txtMaterialCodElim.setForeground(new java.awt.Color(255, 255, 255));
        txtMaterialCodElim.setText("Ingrese código aquí...");
        txtMaterialCodElim.setBorder(null);
        jPanel6.add(txtMaterialCodElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 380, -1));

        jSeparator21.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 380, 10));

        btnEliminarMaterial.setBackground(new java.awt.Color(0, 153, 153));
        btnEliminarMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMaterialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMaterialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMaterialMouseExited(evt);
            }
        });
        btnEliminarMaterial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("ELIMINAR");
        btnEliminarMaterial.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 13, -1, -1));

        jPanel6.add(btnEliminarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 150, 50));

        btnLimpiarElimMat.setBackground(new java.awt.Color(204, 51, 0));
        btnLimpiarElimMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarElimMatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarElimMatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarElimMatMouseExited(evt);
            }
        });
        btnLimpiarElimMat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("LIMPIAR");
        btnLimpiarElimMat.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jPanel6.add(btnLimpiarElimMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 100, 50));

        jLabel49.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Eliminar Material");

        javax.swing.GroupLayout PanelEliminarMaterialLayout = new javax.swing.GroupLayout(PanelEliminarMaterial);
        PanelEliminarMaterial.setLayout(PanelEliminarMaterialLayout);
        PanelEliminarMaterialLayout.setHorizontalGroup(
            PanelEliminarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEliminarMaterialLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addGroup(PanelEliminarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        PanelEliminarMaterialLayout.setVerticalGroup(
            PanelEliminarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEliminarMaterialLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel49)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jPanel9.add(PanelEliminarMaterial, "card4");

        PanelListarMateriales.setBackground(new java.awt.Color(102, 102, 255));
        PanelListarMateriales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelListarMateriales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Listado de Materiales");
        PanelListarMateriales.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        tblListadoMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListadoMateriales);

        PanelListarMateriales.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 779, 290));

        jPanel9.add(PanelListarMateriales, "card5");

        PanelMaterialEspecifico.setBackground(new java.awt.Color(102, 102, 255));
        PanelMaterialEspecifico.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelMaterialEspecifico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(102, 102, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Ingrese Código de Material");
        jPanel7.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtRutFun_Proyecto.setBackground(new java.awt.Color(102, 102, 255));
        txtRutFun_Proyecto.setForeground(new java.awt.Color(255, 255, 255));
        txtRutFun_Proyecto.setText("Ingrese código...");
        txtRutFun_Proyecto.setBorder(null);
        jPanel7.add(txtRutFun_Proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, -1));

        jSeparator22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 250, 10));

        btnBuscarMatEsp.setBackground(new java.awt.Color(255, 204, 51));
        btnBuscarMatEsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMatEspMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMatEspMouseExited(evt);
            }
        });
        btnBuscarMatEsp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("BUSCAR");
        btnBuscarMatEsp.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 13, -1, -1));

        jPanel7.add(btnBuscarMatEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 120, 50));

        PanelMaterialEspecifico.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 430, 100));

        tblMaterialEspecifico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMaterialEspecifico);

        PanelMaterialEspecifico.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 840, 200));

        jLabel51.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Material Específico");
        PanelMaterialEspecifico.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jPanel9.add(PanelMaterialEspecifico, "card6");

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarMaterial.setBackground(new java.awt.Color(204, 0, 0));
        btnBuscarMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMaterialMouseClicked(evt);
            }
        });
        btnBuscarMaterial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Búsqueda");
        btnBuscarMaterial.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BUSCARPRODUCTOESPECIFICO_MATERIALES.png"))); // NOI18N
        btnBuscarMaterial.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 20, 70, -1));

        jPanel3.add(btnBuscarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 140, 130));

        btnIngresarMaterial.setBackground(new java.awt.Color(255, 102, 0));
        btnIngresarMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMaterialMouseClicked(evt);
            }
        });
        btnIngresarMaterial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Insertar");
        btnIngresarMaterial.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/INGRESARMATERIAL_MATERIALES.png"))); // NOI18N
        btnIngresarMaterial.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel3.add(btnIngresarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 130));

        btnEditarMaterial.setBackground(new java.awt.Color(51, 0, 204));
        btnEditarMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMaterialMouseClicked(evt);
            }
        });
        btnEditarMaterial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Editar");
        btnEditarMaterial.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edicion.png"))); // NOI18N
        btnEditarMaterial.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 20, 70, -1));

        jPanel3.add(btnEditarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 140, 130));

        btnPEliminarMaterial.setBackground(new java.awt.Color(204, 0, 204));
        btnPEliminarMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPEliminarMaterialMouseClicked(evt);
            }
        });
        btnPEliminarMaterial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Eliminar");
        btnPEliminarMaterial.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ELIMINAR.png"))); // NOI18N
        btnPEliminarMaterial.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 20, 70, -1));

        jPanel3.add(btnPEliminarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 140, 130));

        btnListarMateriales.setBackground(new java.awt.Color(0, 153, 153));
        btnListarMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarMaterialesMouseClicked(evt);
            }
        });
        btnListarMateriales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Listar");
        btnListarMateriales.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Listar.png"))); // NOI18N
        btnListarMateriales.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 70));

        jPanel3.add(btnListarMateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 140, 130));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtras_Fun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir_Fun)
                        .addGap(13, 13, 13)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)))
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSalir_Fun, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAtras_Fun, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalir_FunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir_FunMouseClicked
        // TODO add your handling code here:
        new Mensajes_SalirAp().setVisible(true);
    }//GEN-LAST:event_btnSalir_FunMouseClicked

    private void btnAtras_FunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtras_FunMouseClicked
        // TODO add your handling code here:
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtras_FunMouseClicked

    void muestraFecha(){
        //Muestra la fecha en el label
        java.util.Date d = new java.util.Date();
        SimpleDateFormat s = new SimpleDateFormat();
        lblDate.setText(s.format(d));
        /*Función para mostrar la fecha actual en el menú*/
    } 
    
    void limpiarCampos(){
        txtNombreMat.setText("");
        txtStockMaterial.setText("");
        txtNombreMatEdit.setText("");
        txtStockMaterialEdit.setText("");
        txtMaterialCodElim.setText("");
        txtIdMaterial.setText("");
    }
    
    void llenarTabla(){
        Conexion con = new Conexion();
        try{
            con.getConexion();
            Statement stmt = con.getConexion().createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM material");
            DefaultTableModel value = new DefaultTableModel();
            tblListadoMateriales.setModel(value);
            value.addColumn("CODIGO MATERIAL");
            value.addColumn("NOMBRE");
            value.addColumn("STOCK");
            while(rs.next()){
                value.addRow(new Object[]{rs.getString("ID_MAT"), rs.getString("NOMBRE_MAT"), rs.getInt("STOCK_MAT")});
            }
            rs.close();
        } catch(SQLException e){
            System.out.println(e);
        }
        
        
    }
    
    private void btnLimpiarMatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMatMouseEntered
        // TODO add your handling code here:
        btnLimpiarMat.setBackground(new Color (255,51,0));
    }//GEN-LAST:event_btnLimpiarMatMouseEntered

    private void btnLimpiarMatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMatMouseExited
        // TODO add your handling code here:
        btnLimpiarMat.setBackground(new Color (204,51,0));
    }//GEN-LAST:event_btnLimpiarMatMouseExited

    private void btnInsertarMatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMatMouseEntered
        // TODO add your handling code here:
        btnInsertarMat.setBackground(new Color (0,204,153));
    }//GEN-LAST:event_btnInsertarMatMouseEntered

    private void btnInsertarMatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMatMouseExited
        // TODO add your handling code here:
        btnInsertarMat.setBackground(new Color (0,153,153));
    }//GEN-LAST:event_btnInsertarMatMouseExited

    private void btnEditarMatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMatMouseEntered
        // TODO add your handling code here:
        btnEditarMat.setBackground(new Color (0,204,153));
    }//GEN-LAST:event_btnEditarMatMouseEntered

    private void btnEditarMatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMatMouseExited
        // TODO add your handling code here:
        btnEditarMat.setBackground(new Color (0,153,153));
    }//GEN-LAST:event_btnEditarMatMouseExited

    private void btnLimpiarEditMatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarEditMatMouseEntered
        // TODO add your handling code here:
        btnLimpiarEditMat.setBackground(new Color (255,51,0));
    }//GEN-LAST:event_btnLimpiarEditMatMouseEntered

    private void btnLimpiarEditMatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarEditMatMouseExited
        // TODO add your handling code here:
        btnLimpiarEditMat.setBackground(new Color (204,51,0));
    }//GEN-LAST:event_btnLimpiarEditMatMouseExited

    private void btnBuscarMatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMatMouseEntered
        // TODO add your handling code here:
        btnBuscarMat.setBackground(new Color (255,204,153));
    }//GEN-LAST:event_btnBuscarMatMouseEntered

    private void btnBuscarMatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMatMouseExited
        // TODO add your handling code here:
        btnBuscarMat.setBackground(new Color (255,204,51));
    }//GEN-LAST:event_btnBuscarMatMouseExited

    private void btnEliminarMaterialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMaterialMouseEntered
        // TODO add your handling code here:
        btnEliminarMaterial.setBackground(new Color (0,204,153));
    }//GEN-LAST:event_btnEliminarMaterialMouseEntered

    private void btnEliminarMaterialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMaterialMouseExited
        // TODO add your handling code here:
        btnEliminarMaterial.setBackground(new Color (0,153,153));
    }//GEN-LAST:event_btnEliminarMaterialMouseExited

    private void btnLimpiarElimMatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarElimMatMouseEntered
        // TODO add your handling code here:
        btnLimpiarElimMat.setBackground(new Color (255,51,0));
    }//GEN-LAST:event_btnLimpiarElimMatMouseEntered

    private void btnLimpiarElimMatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarElimMatMouseExited
        // TODO add your handling code here:
        btnLimpiarElimMat.setBackground(new Color (204,51,0));
    }//GEN-LAST:event_btnLimpiarElimMatMouseExited

    private void btnBuscarMatEspMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMatEspMouseEntered
        // TODO add your handling code here:
        btnBuscarMatEsp.setBackground(new Color (255,204,153));
    }//GEN-LAST:event_btnBuscarMatEspMouseEntered

    private void btnBuscarMatEspMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMatEspMouseExited
        // TODO add your handling code here:
        btnBuscarMatEsp.setBackground(new Color (255,204,51));
    }//GEN-LAST:event_btnBuscarMatEspMouseExited

    private void btnBuscarMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMaterialMouseClicked
        // TODO add your handling code here:
        btnIngresarMaterial.setBackground(new Color (255,102,0));
        btnEditarMaterial.setBackground(new Color (51,0,204));
        btnPEliminarMaterial.setBackground(new Color (204,0,204));
        btnListarMateriales.setBackground(new Color (0,153,153));
        btnBuscarMaterial.setBackground(new Color (255,102,102));

        PanelMenuMateriales.setVisible(false);
        PanelIngresarMateriales.setVisible(false);
        PanelEditarMat.setVisible(false);
        PanelEliminarMaterial.setVisible(false);
        PanelListarMateriales.setVisible(false);
        PanelMaterialEspecifico.setVisible(true);
    }//GEN-LAST:event_btnBuscarMaterialMouseClicked

    private void btnIngresarMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMaterialMouseClicked
        // TODO add your handling code here:

        btnIngresarMaterial.setBackground(new Color (255,204,153));
        btnEditarMaterial.setBackground(new Color (51,0,204));
        btnPEliminarMaterial.setBackground(new Color (204,0,204));
        btnListarMateriales.setBackground(new Color (0,153,153));
        btnBuscarMaterial.setBackground(new Color (204,0,0));

        PanelMenuMateriales.setVisible(false);
        PanelIngresarMateriales.setVisible(true);
        PanelEditarMat.setVisible(false);
        PanelEliminarMaterial.setVisible(false);
        PanelListarMateriales.setVisible(false);
        PanelMaterialEspecifico.setVisible(false);
    }//GEN-LAST:event_btnIngresarMaterialMouseClicked

    private void btnEditarMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMaterialMouseClicked
        // TODO add your handling code here:
        btnIngresarMaterial.setBackground(new Color (255,102,0));
        btnEditarMaterial.setBackground(new Color (204,204,255));
        btnPEliminarMaterial.setBackground(new Color (204,0,204));
        btnListarMateriales.setBackground(new Color (0,153,153));
        btnBuscarMaterial.setBackground(new Color (204,0,0));

        PanelMenuMateriales.setVisible(false);
        PanelIngresarMateriales.setVisible(false);
        PanelEditarMat.setVisible(true);
        PanelEliminarMaterial.setVisible(false);
        PanelListarMateriales.setVisible(false);
        PanelMaterialEspecifico.setVisible(false);
    }//GEN-LAST:event_btnEditarMaterialMouseClicked

    private void btnPEliminarMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPEliminarMaterialMouseClicked
        // TODO add your handling code here:
        btnIngresarMaterial.setBackground(new Color (255,102,0));
        btnEditarMaterial.setBackground(new Color (51,0,204));
        btnPEliminarMaterial.setBackground(new Color (255,153,255));
        btnListarMateriales.setBackground(new Color (0,153,153));
        btnBuscarMaterial.setBackground(new Color (204,0,0));

        PanelMenuMateriales.setVisible(false);
        PanelIngresarMateriales.setVisible(false);
        PanelEditarMat.setVisible(false);
        PanelEliminarMaterial.setVisible(true);
        PanelListarMateriales.setVisible(false);
        PanelMaterialEspecifico.setVisible(false);
    }//GEN-LAST:event_btnPEliminarMaterialMouseClicked

    private void btnListarMaterialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMaterialesMouseClicked
        // TODO add your handling code here:
        btnIngresarMaterial.setBackground(new Color (255,102,0));
        btnEditarMaterial.setBackground(new Color (51,0,204));
        btnPEliminarMaterial.setBackground(new Color (204,0,204));
        btnListarMateriales.setBackground(new Color (0,204,153));
        btnBuscarMaterial.setBackground(new Color (204,0,0));

        PanelMenuMateriales.setVisible(false);
        PanelIngresarMateriales.setVisible(false);
        PanelEditarMat.setVisible(false);
        PanelEliminarMaterial.setVisible(false);
        PanelListarMateriales.setVisible(true);
        PanelMaterialEspecifico.setVisible(false);
        
        llenarTabla();
    }//GEN-LAST:event_btnListarMaterialesMouseClicked

    private void btnLimpiarMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMatMouseClicked
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarMatMouseClicked

    private void btnLimpiarEditMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarEditMatMouseClicked
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarEditMatMouseClicked

    private void btnLimpiarElimMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarElimMatMouseClicked
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarElimMatMouseClicked

    private void btnInsertarMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMatMouseClicked
        // TODO add your handling code here:
        
        MaterialConsultas mc = new MaterialConsultas();
        try{
            mc.agregarMaterial(txtNombreMat.getText(), Integer.parseInt(txtStockMaterial.getText()));
            JOptionPane.showMessageDialog(null, "Registrar", "Registro Exitoso", 1);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error", "Registro no Exitoso", 1);   
        }
        
    }//GEN-LAST:event_btnInsertarMatMouseClicked

    private void btnEliminarMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMaterialMouseClicked
        // TODO add your handling code here:
        MaterialConsultas mc = new MaterialConsultas();
        try{
            mc.eliminarMaterial(txtMaterialCodElim.getText());
            JOptionPane.showMessageDialog(null, "Eliminar", "Eliminado con Exito", 1);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error", "Eliminado sin Exito", 1);
        }
    }//GEN-LAST:event_btnEliminarMaterialMouseClicked

    private void btnBuscarMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMatMouseClicked
        // TODO add your handling code here:
        Conexion con = new Conexion();
        
        try{
            con.getConexion();
            Statement stmt = con.getConexion().createStatement();
            try{
                ResultSet rs = stmt.executeQuery("SELECT * FROM MATERIAL WHERE ID_MAT ='"+txtIdMaterial.getText()+"'");
                while(rs.next()){
                    txtNombreMatEdit.setText(rs.getString("NOMBRE_MAT"));
                    txtStockMaterialEdit.setText(rs.getString("STOCK_MAT"));
                }       
                
            } catch (SQLException ex){
                
                System.out.println(ex);
            }            
        } catch (SQLException ex){
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_btnBuscarMatMouseClicked

    private void btnEditarMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMatMouseClicked
        // TODO add your handling code here:
        MaterialConsultas mc = new MaterialConsultas();
        try{
            
            mc.editarMaterial(txtIdMaterial.getText(), txtNombreMatEdit.getText(), Integer.parseInt(txtStockMaterialEdit.getText()));
            JOptionPane.showMessageDialog(null, "Actualizar", "Actualizado", 1);            
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error", "Registro no Actualizado", 1); 
        }
        
    }//GEN-LAST:event_btnEditarMatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Materiales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEditarMat;
    private javax.swing.JPanel PanelEliminarMaterial;
    private javax.swing.JPanel PanelIngresarMateriales;
    private javax.swing.JPanel PanelListarMateriales;
    private javax.swing.JPanel PanelMaterialEspecifico;
    private javax.swing.JPanel PanelMenuMateriales;
    private javax.swing.JLabel btnAtras_Fun;
    private javax.swing.JPanel btnBuscarMat;
    private javax.swing.JPanel btnBuscarMatEsp;
    private javax.swing.JPanel btnBuscarMaterial;
    private javax.swing.JPanel btnEditarMat;
    private javax.swing.JPanel btnEditarMaterial;
    private javax.swing.JPanel btnEliminarMaterial;
    private javax.swing.JPanel btnIngresarMaterial;
    private javax.swing.JPanel btnInsertarMat;
    private javax.swing.JPanel btnLimpiarEditMat;
    private javax.swing.JPanel btnLimpiarElimMat;
    private javax.swing.JPanel btnLimpiarMat;
    private javax.swing.JPanel btnListarMateriales;
    private javax.swing.JPanel btnPEliminarMaterial;
    private javax.swing.JLabel btnSalir_Fun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTable tblListadoMateriales;
    private javax.swing.JTable tblMaterialEspecifico;
    private javax.swing.JTextField txtIdMaterial;
    private javax.swing.JTextField txtMaterialCodElim;
    private javax.swing.JTextField txtNombreMat;
    private javax.swing.JTextField txtNombreMatEdit;
    private javax.swing.JTextField txtRutFun_Proyecto;
    private javax.swing.JTextField txtStockMaterial;
    private javax.swing.JTextField txtStockMaterialEdit;
    // End of variables declaration//GEN-END:variables
}
