/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.Conexion;
import Negocio.TInspecciones;
import Negocio.TReunion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esteban
 */
public class GUI_Reuniones_Inspecciones extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Reuniones
     */
    int xMouse;
    int yMouse; 
    public GUI_Reuniones_Inspecciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        llenar_tblSeguimientoReuniones();
        llenar_tblSeguimientoInspecciones();
        llenar_cmbHitoReunion();
        llenar_cmbHitoInspeccion();
    }
    
    void llenar_cmbHitoInspeccion(){
    Conexion con = new Conexion();
        try{
            con.getConexion();
            Statement stmt = con.getConexion().createStatement();
            try(ResultSet rs = stmt.executeQuery("SELECT * FROM HITO")){
                DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
                modeloCombo.addElement("Seleccionar");
                cmbHitoInspeccion.setModel(modeloCombo);
                while(rs.next()){
                   // Maqui_Herra mh = new Maqui_Herra(rs.getString("NOMBRE_MH"));
                    modeloCombo.addElement(rs.getString("ID_HITO"));
                    cmbHitoInspeccion.setModel(modeloCombo);
                }               
                
            }
            
        }catch (SQLException e) {
            System.out.println(e);
        }
    }
    
    void llenar_cmbHitoReunion(){
    Conexion con = new Conexion();
        try{
            con.getConexion();
            Statement stmt = con.getConexion().createStatement();
            try(ResultSet rs = stmt.executeQuery("SELECT * FROM HITO")){
                DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
                modeloCombo.addElement("Seleccionar");
                cmbHitoReunion.setModel(modeloCombo);
                while(rs.next()){
                   // Maqui_Herra mh = new Maqui_Herra(rs.getString("NOMBRE_MH"));
                    modeloCombo.addElement(rs.getString("ID_HITO"));
                    cmbHitoReunion.setModel(modeloCombo);
                }               
                
            }
            
        }catch (SQLException e) {
            System.out.println(e);
        }
    }

    void llenar_tblSeguimientoReuniones(){
        Conexion con = new Conexion();
        try{
            con.getConexion();
            Statement stmt = con.getConexion().createStatement();
            try(ResultSet rs = stmt.executeQuery("SELECT * FROM ACTA_REUNION")){
                DefaultTableModel modeloTabla = new DefaultTableModel();
                tblSeguimientoReuniones.setModel(modeloTabla);
                modeloTabla.addColumn("NOMBRE");
                modeloTabla.addColumn("CITADOR"); 
                modeloTabla.addColumn("DESCRIPCION"); 
                modeloTabla.addColumn("FECHA"); 
                while(rs.next()){
                   modeloTabla.addRow(new Object[]{ rs.getString("ID_REUN"),rs.getString("CITADOR_REUN"),
                   rs.getString("MOTIVO_REUN"), rs.getDate("FECHA_REUN")});
                }               
                
            }
            
        }catch (SQLException e) {
            System.out.println(e);
        }
    }
    
    void llenar_tblSeguimientoInspecciones(){
        Conexion con = new Conexion();
        try{
            con.getConexion();
            Statement stmt = con.getConexion().createStatement();
            try(ResultSet rs = stmt.executeQuery("SELECT * FROM ACTA_REUNION")){
                DefaultTableModel modeloTabla = new DefaultTableModel();
                tblSeguimientoInspecciones.setModel(modeloTabla);
                modeloTabla.addColumn("NOMBRE");
                modeloTabla.addColumn("CITADOR"); 
                modeloTabla.addColumn("DESCRIPCION"); 
                modeloTabla.addColumn("FECHA"); 
                while(rs.next()){
                   modeloTabla.addRow(new Object[]{ rs.getString("ID_REUN"),rs.getString("CITADOR_REUN"),
                   rs.getString("MOTIVO_REUN"), rs.getDate("FECHA_REUN")});
                }               
                
            }
            
        }catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir_Fun = new javax.swing.JLabel();
        btnAtras_Fun = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblDate = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        PanelMenuReuniones = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        PanelRegistrarReunion = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnLimpiarFun = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        txtNombreCitador = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnRegistrarReunion = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSeleccionarObra_Reunion = new javax.swing.JTable();
        jLabel57 = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel59 = new javax.swing.JLabel();
        txtHoraTermino = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        jLabel70 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        jLabel71 = new javax.swing.JLabel();
        txtFechaReunion = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        cmbHitoReunion = new javax.swing.JComboBox<>();
        PanelRegistrarInspeccion = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnLimpiarInspeccion = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txtInspector = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        btnRegistrarInspeccion = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblSeleccionarObra_RegInspecciones = new javax.swing.JTable();
        jLabel72 = new javax.swing.JLabel();
        txtDescripcionInspeccion = new javax.swing.JTextField();
        jSeparator33 = new javax.swing.JSeparator();
        jLabel73 = new javax.swing.JLabel();
        txtPorcentajeAvance = new javax.swing.JTextField();
        jSeparator34 = new javax.swing.JSeparator();
        jLabel74 = new javax.swing.JLabel();
        cmbHitoInspeccion = new javax.swing.JComboBox<>();
        PanelReuniones = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSeleccionarObra_Reunion_Seguimiento = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblSeguimientoReuniones = new javax.swing.JTable();
        PanelSeguimientoInspecciones = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblSeguimientoInspecciones = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblSeleccionarObra_Inspecciones = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnIngresarFuncionario = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnEditarFuncionario = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnEliminarFuncionario = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnListarFuncionario = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Drag = new javax.swing.JPanel();
        FrameDrag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.CardLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 699, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 19, -1, -1));

        btnSalir_Fun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CERRAR_MINI_ICON.png"))); // NOI18N
        btnSalir_Fun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalir_FunMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir_Fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(966, 15, -1, -1));

        btnAtras_Fun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ATRAS_MINI_ICON.png"))); // NOI18N
        btnAtras_Fun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtras_FunMouseClicked(evt);
            }
        });
        jPanel1.add(btnAtras_Fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 15, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("USER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 19, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/USER_MINI_ICON_MAINMENU.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 23, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSTRUCTORA VIALIS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 14, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CALENDARIO_MINI_ICON_MAINMENU.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 23, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, 1003, 15));

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("jLabel6");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 23, -1, -1));

        jPanel9.setBackground(new java.awt.Color(102, 102, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel9.setLayout(new java.awt.CardLayout());

        PanelMenuReuniones.setBackground(new java.awt.Color(102, 102, 255));
        PanelMenuReuniones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("¡Bienvenido al menú de Reuniones e Inspecciones!");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Utiliza diversas herramientas para el control y gestión de los funcionarios Vialis");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/REUNIONINSPECCION_MENUPRINCIPAL.png"))); // NOI18N

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Funciones disponibles: ");

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("1.- Registrar Reunión o Inspección");

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("2.- Eliminación de Reunión/Inspección");

        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("3.- Registros Almacenados");

        javax.swing.GroupLayout PanelMenuReunionesLayout = new javax.swing.GroupLayout(PanelMenuReuniones);
        PanelMenuReuniones.setLayout(PanelMenuReunionesLayout);
        PanelMenuReunionesLayout.setHorizontalGroup(
            PanelMenuReunionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuReunionesLayout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addGroup(PanelMenuReunionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(PanelMenuReunionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(PanelMenuReunionesLayout.createSequentialGroup()
                            .addGroup(PanelMenuReunionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel54)
                                .addComponent(jLabel55)
                                .addComponent(jLabel56)
                                .addComponent(jLabel58))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11))
                        .addComponent(jLabel52)))
                .addGap(234, 234, 234))
        );
        PanelMenuReunionesLayout.setVerticalGroup(
            PanelMenuReunionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuReunionesLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel52)
                .addGroup(PanelMenuReunionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuReunionesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel58))
                    .addGroup(PanelMenuReunionesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel11)))
                .addContainerGap(310, Short.MAX_VALUE))
        );

        jPanel9.add(PanelMenuReuniones, "card7");

        PanelRegistrarReunion.setBackground(new java.awt.Color(102, 102, 255));
        PanelRegistrarReunion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelRegistrarReunion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Registro de Reunión");
        PanelRegistrarReunion.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Seleccione obra:");
        PanelRegistrarReunion.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Hito:");
        PanelRegistrarReunion.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        btnLimpiarFun.setBackground(new java.awt.Color(204, 51, 0));
        btnLimpiarFun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarFunMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarFunMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarFunMouseExited(evt);
            }
        });
        btnLimpiarFun.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("LIMPIAR");
        btnLimpiarFun.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 13, -1, -1));

        PanelRegistrarReunion.add(btnLimpiarFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 150, 50));

        txtNombreCitador.setBackground(new java.awt.Color(102, 102, 255));
        txtNombreCitador.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCitador.setText("Ingrese nombre de citador...");
        txtNombreCitador.setBorder(null);
        txtNombreCitador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreCitadorMouseClicked(evt);
            }
        });
        PanelRegistrarReunion.add(txtNombreCitador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 189, -1));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        PanelRegistrarReunion.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 189, -1));

        btnRegistrarReunion.setBackground(new java.awt.Color(0, 153, 153));
        btnRegistrarReunion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarReunionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarReunionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarReunionMouseExited(evt);
            }
        });
        btnRegistrarReunion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("REGISTRAR");
        btnRegistrarReunion.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, -1));

        PanelRegistrarReunion.add(btnRegistrarReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 150, 50));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(null);
        jScrollPane4.setForeground(new java.awt.Color(255, 255, 255));

        tblSeleccionarObra_Reunion.setBackground(new java.awt.Color(252, 251, 251));
        tblSeleccionarObra_Reunion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSeleccionarObra_Reunion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Puente Cau Cau"},
                {"Castillo Ratinbum"},
                {"Centro Pokémon"},
                {"Acuario de Jureles"}
            },
            new String [] {
                "NOMBRE DE OBRA"
            }
        ));
        tblSeleccionarObra_Reunion.setGridColor(new java.awt.Color(255, 255, 255));
        tblSeleccionarObra_Reunion.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSeleccionarObra_Reunion.setShowHorizontalLines(false);
        tblSeleccionarObra_Reunion.setShowVerticalLines(false);
        tblSeleccionarObra_Reunion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccionarObra_ReunionMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblSeleccionarObra_Reunion);

        PanelRegistrarReunion.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 640, 130));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Hora de Inicio:");
        PanelRegistrarReunion.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        txtHoraInicio.setBackground(new java.awt.Color(102, 102, 255));
        txtHoraInicio.setForeground(new java.awt.Color(255, 255, 255));
        txtHoraInicio.setText("Ingrese hora de inicio...");
        txtHoraInicio.setBorder(null);
        txtHoraInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHoraInicioMouseClicked(evt);
            }
        });
        PanelRegistrarReunion.add(txtHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 189, -1));

        jSeparator27.setForeground(new java.awt.Color(255, 255, 255));
        PanelRegistrarReunion.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 189, -1));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Hora de Término:");
        PanelRegistrarReunion.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        txtHoraTermino.setBackground(new java.awt.Color(102, 102, 255));
        txtHoraTermino.setForeground(new java.awt.Color(255, 255, 255));
        txtHoraTermino.setText("Ingrese hora de término...");
        txtHoraTermino.setBorder(null);
        txtHoraTermino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHoraTerminoMouseClicked(evt);
            }
        });
        PanelRegistrarReunion.add(txtHoraTermino, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 189, -1));

        jSeparator28.setForeground(new java.awt.Color(255, 255, 255));
        PanelRegistrarReunion.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 189, -1));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Motivo:");
        PanelRegistrarReunion.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        txtMotivo.setBackground(new java.awt.Color(102, 102, 255));
        txtMotivo.setForeground(new java.awt.Color(255, 255, 255));
        txtMotivo.setText("Ingrese motivo...");
        txtMotivo.setBorder(null);
        txtMotivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMotivoMouseClicked(evt);
            }
        });
        PanelRegistrarReunion.add(txtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 189, -1));

        jSeparator29.setForeground(new java.awt.Color(255, 255, 255));
        PanelRegistrarReunion.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 189, -1));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Fecha de Reunión:");
        PanelRegistrarReunion.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        txtFechaReunion.setBackground(new java.awt.Color(102, 102, 255));
        txtFechaReunion.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaReunion.setText("DD/MM/AAAA");
        txtFechaReunion.setBorder(null);
        txtFechaReunion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaReunionMouseClicked(evt);
            }
        });
        PanelRegistrarReunion.add(txtFechaReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 189, -1));

        jSeparator30.setForeground(new java.awt.Color(255, 255, 255));
        PanelRegistrarReunion.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 189, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Citador:");
        PanelRegistrarReunion.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        cmbHitoReunion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PanelRegistrarReunion.add(cmbHitoReunion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 190, -1));

        jPanel9.add(PanelRegistrarReunion, "card2");

        PanelRegistrarInspeccion.setBackground(new java.awt.Color(102, 102, 255));
        PanelRegistrarInspeccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelRegistrarInspeccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Registro de Inspección");
        PanelRegistrarInspeccion.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Seleccione obra:");
        PanelRegistrarInspeccion.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Inspector:");
        PanelRegistrarInspeccion.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        btnLimpiarInspeccion.setBackground(new java.awt.Color(204, 51, 0));
        btnLimpiarInspeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarInspeccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarInspeccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarInspeccionMouseExited(evt);
            }
        });
        btnLimpiarInspeccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("LIMPIAR");
        btnLimpiarInspeccion.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 13, -1, -1));

        PanelRegistrarInspeccion.add(btnLimpiarInspeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 150, 50));

        txtInspector.setBackground(new java.awt.Color(102, 102, 255));
        txtInspector.setForeground(new java.awt.Color(255, 255, 255));
        txtInspector.setText("Ingrese Inspector...");
        txtInspector.setBorder(null);
        txtInspector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtInspectorMouseClicked(evt);
            }
        });
        PanelRegistrarInspeccion.add(txtInspector, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 189, -1));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        PanelRegistrarInspeccion.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 189, -1));

        btnRegistrarInspeccion.setBackground(new java.awt.Color(0, 153, 153));
        btnRegistrarInspeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarInspeccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarInspeccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarInspeccionMouseExited(evt);
            }
        });
        btnRegistrarInspeccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("REGISTRAR");
        btnRegistrarInspeccion.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, -1));

        PanelRegistrarInspeccion.add(btnRegistrarInspeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 150, 50));

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setBorder(null);
        jScrollPane5.setForeground(new java.awt.Color(255, 255, 255));

        tblSeleccionarObra_RegInspecciones.setBackground(new java.awt.Color(252, 251, 251));
        tblSeleccionarObra_RegInspecciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSeleccionarObra_RegInspecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Puente Cau Cau"},
                {"Castillo Ratinbum"},
                {"Centro Pokémon"},
                {"Acuario de Jureles"}
            },
            new String [] {
                "NOMBRE DE OBRA"
            }
        ));
        tblSeleccionarObra_RegInspecciones.setGridColor(new java.awt.Color(255, 255, 255));
        tblSeleccionarObra_RegInspecciones.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSeleccionarObra_RegInspecciones.setShowHorizontalLines(false);
        tblSeleccionarObra_RegInspecciones.setShowVerticalLines(false);
        tblSeleccionarObra_RegInspecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccionarObra_RegInspeccionesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblSeleccionarObra_RegInspecciones);

        PanelRegistrarInspeccion.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 640, 130));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Descripción:");
        PanelRegistrarInspeccion.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        txtDescripcionInspeccion.setBackground(new java.awt.Color(102, 102, 255));
        txtDescripcionInspeccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcionInspeccion.setText("Ingrese descripción...");
        txtDescripcionInspeccion.setBorder(null);
        txtDescripcionInspeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDescripcionInspeccionMouseClicked(evt);
            }
        });
        PanelRegistrarInspeccion.add(txtDescripcionInspeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 189, -1));

        jSeparator33.setForeground(new java.awt.Color(255, 255, 255));
        PanelRegistrarInspeccion.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 189, -1));

        jLabel73.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Hito:");
        PanelRegistrarInspeccion.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        txtPorcentajeAvance.setBackground(new java.awt.Color(102, 102, 255));
        txtPorcentajeAvance.setForeground(new java.awt.Color(255, 255, 255));
        txtPorcentajeAvance.setText("Ingrese porcentaje (numero)...");
        txtPorcentajeAvance.setBorder(null);
        txtPorcentajeAvance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPorcentajeAvanceMouseClicked(evt);
            }
        });
        PanelRegistrarInspeccion.add(txtPorcentajeAvance, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 189, -1));

        jSeparator34.setForeground(new java.awt.Color(255, 255, 255));
        PanelRegistrarInspeccion.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 189, -1));

        jLabel74.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Porcentaje de avance:");
        PanelRegistrarInspeccion.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        cmbHitoInspeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PanelRegistrarInspeccion.add(cmbHitoInspeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 190, -1));

        jPanel9.add(PanelRegistrarInspeccion, "card2");

        PanelReuniones.setBackground(new java.awt.Color(102, 102, 255));
        PanelReuniones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel49.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Seguimiento de Reuniones");

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setBorder(null);
        jScrollPane6.setForeground(new java.awt.Color(255, 255, 255));

        tblSeleccionarObra_Reunion_Seguimiento.setBackground(new java.awt.Color(252, 251, 251));
        tblSeleccionarObra_Reunion_Seguimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSeleccionarObra_Reunion_Seguimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Puente Cau Cau"},
                {"Castillo Ratinbum"},
                {"Centro Pokémon"},
                {"Acuario de Jureles"}
            },
            new String [] {
                "NOMBRE DE OBRA"
            }
        ));
        tblSeleccionarObra_Reunion_Seguimiento.setGridColor(new java.awt.Color(255, 255, 255));
        tblSeleccionarObra_Reunion_Seguimiento.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSeleccionarObra_Reunion_Seguimiento.setShowHorizontalLines(false);
        tblSeleccionarObra_Reunion_Seguimiento.setShowVerticalLines(false);
        tblSeleccionarObra_Reunion_Seguimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccionarObra_Reunion_SeguimientoMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblSeleccionarObra_Reunion_Seguimiento);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Seleccione obra:");

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane7.setBorder(null);
        jScrollPane7.setForeground(new java.awt.Color(255, 255, 255));

        tblSeguimientoReuniones.setBackground(new java.awt.Color(252, 251, 251));
        tblSeguimientoReuniones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSeguimientoReuniones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Cindy Ente", "Análisis de Riesgo", "22/06/2018"},
                {"2", "Alan brito", "Estuio de Mercado", "23/06/2018"},
                {"3", "Soyla Cerda", "Construccion con retraso", "25/06/2018"},
                {"4", "Elsa Capunta", "Avances", "30/06/2018"},
                {"5", "Elva Zurita", "Avances", "03/07/2018"}
            },
            new String [] {
                "ID", "Citador", "Descripcion", "Fecha"
            }
        ));
        tblSeguimientoReuniones.setGridColor(new java.awt.Color(255, 255, 255));
        tblSeguimientoReuniones.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSeguimientoReuniones.setShowHorizontalLines(false);
        tblSeguimientoReuniones.setShowVerticalLines(false);
        tblSeguimientoReuniones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeguimientoReunionesMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblSeguimientoReuniones);

        javax.swing.GroupLayout PanelReunionesLayout = new javax.swing.GroupLayout(PanelReuniones);
        PanelReuniones.setLayout(PanelReunionesLayout);
        PanelReunionesLayout.setHorizontalGroup(
            PanelReunionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelReunionesLayout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addGroup(PanelReunionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel49)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
        PanelReunionesLayout.setVerticalGroup(
            PanelReunionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReunionesLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel9.add(PanelReuniones, "card4");

        PanelSeguimientoInspecciones.setBackground(new java.awt.Color(102, 102, 255));
        PanelSeguimientoInspecciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelSeguimientoInspecciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Seguimiento de Inspecciones");
        PanelSeguimientoInspecciones.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jScrollPane8.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane8.setBorder(null);
        jScrollPane8.setForeground(new java.awt.Color(255, 255, 255));

        tblSeguimientoInspecciones.setBackground(new java.awt.Color(252, 251, 251));
        tblSeguimientoInspecciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSeguimientoInspecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Cindy Ente", "Análisis de Riesgo", "22/06/2018"},
                {"2", "Alan brito", "Estuio de Mercado", "23/06/2018"},
                {"3", "Soyla Cerda", "Construccion con retraso", "25/06/2018"},
                {"4", "Elsa Capunta", "Avances", "30/06/2018"},
                {"5", "Elva Zurita", "Avances", "03/07/2018"}
            },
            new String [] {
                "ID", "Citador", "Descripcion", "Fecha"
            }
        ));
        tblSeguimientoInspecciones.setGridColor(new java.awt.Color(255, 255, 255));
        tblSeguimientoInspecciones.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSeguimientoInspecciones.setShowHorizontalLines(false);
        tblSeguimientoInspecciones.setShowVerticalLines(false);
        tblSeguimientoInspecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeguimientoInspeccionesMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblSeguimientoInspecciones);

        PanelSeguimientoInspecciones.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 600, 150));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Seleccione obra:");
        PanelSeguimientoInspecciones.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jScrollPane9.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane9.setBorder(null);
        jScrollPane9.setForeground(new java.awt.Color(255, 255, 255));

        tblSeleccionarObra_Inspecciones.setBackground(new java.awt.Color(252, 251, 251));
        tblSeleccionarObra_Inspecciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSeleccionarObra_Inspecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Puente Cau Cau"},
                {"Castillo Ratinbum"},
                {"Centro Pokémon"},
                {"Acuario de Jureles"}
            },
            new String [] {
                "NOMBRE DE OBRA"
            }
        ));
        tblSeleccionarObra_Inspecciones.setGridColor(new java.awt.Color(255, 255, 255));
        tblSeleccionarObra_Inspecciones.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSeleccionarObra_Inspecciones.setShowHorizontalLines(false);
        tblSeleccionarObra_Inspecciones.setShowVerticalLines(false);
        tblSeleccionarObra_Inspecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccionarObra_InspeccionesMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tblSeleccionarObra_Inspecciones);

        PanelSeguimientoInspecciones.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 600, 130));

        jPanel9.add(PanelSeguimientoInspecciones, "card5");

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 217, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresarFuncionario.setBackground(new java.awt.Color(255, 102, 0));
        btnIngresarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarFuncionarioMouseClicked(evt);
            }
        });
        btnIngresarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registrar Reunión");
        btnIngresarFuncionario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/REUNION_REGISTRARREUNION.png"))); // NOI18N
        btnIngresarFuncionario.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel3.add(btnIngresarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 130));

        btnEditarFuncionario.setBackground(new java.awt.Color(51, 0, 204));
        btnEditarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarFuncionarioMouseClicked(evt);
            }
        });
        btnEditarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registrar Inspección");
        btnEditarFuncionario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/INSPECCIONES_REGISTROINSPECCIONES.png"))); // NOI18N
        btnEditarFuncionario.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, -1));

        jPanel3.add(btnEditarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 140, 130));

        btnEliminarFuncionario.setBackground(new java.awt.Color(204, 0, 204));
        btnEliminarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarFuncionarioMouseClicked(evt);
            }
        });
        btnEliminarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/REUNIONES_LISTADOREUNIONES.png"))); // NOI18N
        btnEliminarFuncionario.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 70));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Reuniones");
        btnEliminarFuncionario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, -1));

        jPanel3.add(btnEliminarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 140, 130));

        btnListarFuncionario.setBackground(new java.awt.Color(0, 153, 153));
        btnListarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarFuncionarioMouseClicked(evt);
            }
        });
        btnListarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/INSPECCIONES_LISTADOINSPECCIONES.png"))); // NOI18N
        btnListarFuncionario.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Inspecciones");
        btnListarFuncionario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jPanel3.add(btnListarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 140, 130));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 80, -1, -1));

        Drag.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout DragLayout = new javax.swing.GroupLayout(Drag);
        Drag.setLayout(DragLayout);
        DragLayout.setHorizontalGroup(
            DragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        DragLayout.setVerticalGroup(
            DragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(Drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 60));

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FrameDragMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        jPanel1.add(FrameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalir_FunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir_FunMouseClicked
        // TODO add your handling code here:
        new Mensajes_SalirAp().setVisible(true);
    }//GEN-LAST:event_btnSalir_FunMouseClicked

    private void btnAtras_FunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtras_FunMouseClicked
        // TODO add your handling code here:
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtras_FunMouseClicked

    private void btnLimpiarFunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFunMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnLimpiarFunMouseClicked

    private void btnLimpiarFunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFunMouseEntered
        // TODO add your handling code here:
        btnLimpiarFun.setBackground(new Color (255,51,0));
    }//GEN-LAST:event_btnLimpiarFunMouseEntered

    private void btnLimpiarFunMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFunMouseExited
        // TODO add your handling code here:
        btnLimpiarFun.setBackground(new Color (204,51,0));
    }//GEN-LAST:event_btnLimpiarFunMouseExited

    private void btnRegistrarReunionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarReunionMouseClicked
        TReunion tr = new TReunion();
        DefaultTableModel modeloTabla = (DefaultTableModel)tblSeleccionarObra_Reunion.getModel();
        String dato = String.valueOf(modeloTabla.getValueAt(tblSeleccionarObra_Reunion.getSelectedRow(),0));
        Conexion con = new Conexion();
        int id_hi = 0;
        try{
            con.getConexion();
            Statement stmt = con.getConexion().createStatement();
            try{
                ResultSet rs = stmt.executeQuery("SELECT ID_HITO FROM HITO WHERE NOMBRE_HITO ='"+cmbHitoReunion.getSelectedItem().toString()+"'");
                while(rs.next()){
                    String id = rs.getString("ID_HITO");
                    id_hi = Integer.parseInt(id);
                }                
            }catch (SQLException ex){
                System.out.println(ex);
            }
        }catch(Exception ex){
            
        }
        
        try{
            tr.registrarReunion(txtNombreCitador.getText(),
                    txtHoraInicio.getText(),
                    txtHoraTermino.getText(), 
                    txtMotivo.getText(), 
                    txtFechaReunion.getText(), 
                    id_hi, dato);
            new Mensajes_ExitoIngreso().setVisible(true);
        }catch(Exception ex){
            new Mensajes_ErrorIngresar().setVisible(true);
        }
        
    }//GEN-LAST:event_btnRegistrarReunionMouseClicked

    private void btnRegistrarReunionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarReunionMouseEntered
        // TODO add your handling code here:
        btnRegistrarReunion.setBackground(new Color (0,204,153));
    }//GEN-LAST:event_btnRegistrarReunionMouseEntered

    private void btnRegistrarReunionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarReunionMouseExited
        // TODO add your handling code here:
        btnRegistrarReunion.setBackground(new Color (0,153,153));
    }//GEN-LAST:event_btnRegistrarReunionMouseExited

    private void btnIngresarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarFuncionarioMouseClicked
        // TODO add your handling code here:

        btnIngresarFuncionario.setBackground(new Color (255,204,153));
        btnEditarFuncionario.setBackground(new Color (51,0,204));
        btnEliminarFuncionario.setBackground(new Color (204,0,204));
        btnListarFuncionario.setBackground(new Color (0,153,153));

        PanelMenuReuniones.setVisible(false);
        PanelRegistrarReunion.setVisible(true);
        PanelRegistrarInspeccion.setVisible(false);
        PanelReuniones.setVisible(false);
        PanelSeguimientoInspecciones.setVisible(false);

    }//GEN-LAST:event_btnIngresarFuncionarioMouseClicked

    private void btnEditarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarFuncionarioMouseClicked
        // TODO add your handling code here:
        btnIngresarFuncionario.setBackground(new Color (255,102,0));
        btnEditarFuncionario.setBackground(new Color (204,204,255));
        btnEliminarFuncionario.setBackground(new Color (204,0,204));
        btnListarFuncionario.setBackground(new Color (0,153,153));


        PanelMenuReuniones.setVisible(false);
        PanelRegistrarReunion.setVisible(false);
        PanelRegistrarInspeccion.setVisible(true);
        PanelReuniones.setVisible(false);
        PanelSeguimientoInspecciones.setVisible(false);

    }//GEN-LAST:event_btnEditarFuncionarioMouseClicked

    private void tblSeleccionarObra_ReunionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccionarObra_ReunionMouseClicked

    }//GEN-LAST:event_tblSeleccionarObra_ReunionMouseClicked

    private void txtNombreCitadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreCitadorMouseClicked
        // TODO add your handling code here:
        txtNombreCitador.setText("");
    }//GEN-LAST:event_txtNombreCitadorMouseClicked

    private void txtHoraInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHoraInicioMouseClicked
        // TODO add your handling code here:
        txtHoraInicio.setText("");
    }//GEN-LAST:event_txtHoraInicioMouseClicked

    private void txtHoraTerminoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHoraTerminoMouseClicked
        // TODO add your handling code here:
        txtHoraTermino.setText("");
    }//GEN-LAST:event_txtHoraTerminoMouseClicked

    private void txtMotivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMotivoMouseClicked
        // TODO add your handling code here:
        txtMotivo.setText("");
    }//GEN-LAST:event_txtMotivoMouseClicked

    private void txtFechaReunionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaReunionMouseClicked
        // TODO add your handling code here:
        txtFechaReunion.setText("");
    }//GEN-LAST:event_txtFechaReunionMouseClicked

    private void btnLimpiarInspeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarInspeccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarInspeccionMouseClicked

    private void btnLimpiarInspeccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarInspeccionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarInspeccionMouseEntered

    private void btnLimpiarInspeccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarInspeccionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarInspeccionMouseExited

    private void txtInspectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInspectorMouseClicked
        // TODO add your handling code here:
        txtInspector.setText("");
    }//GEN-LAST:event_txtInspectorMouseClicked

    private void btnRegistrarInspeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarInspeccionMouseClicked
        TInspecciones ti = new TInspecciones();
        DefaultTableModel modeloTabla = (DefaultTableModel)tblSeleccionarObra_RegInspecciones.getModel();
        String dato = String.valueOf(modeloTabla.getValueAt(tblSeleccionarObra_RegInspecciones.getSelectedRow(),0));
        Conexion con = new Conexion();
        int id_hi = 0;
        try{
            con.getConexion();
            Statement stmt = con.getConexion().createStatement();
            try{
                ResultSet rs = stmt.executeQuery("SELECT ID_HITO FROM HITO WHERE NOMBRE_HITO ='"+cmbHitoInspeccion.getSelectedItem().toString()+"'");
                while(rs.next()){
                    String id = rs.getString("ID_HITO");
                    id_hi = Integer.parseInt(id);
                }                
            }catch (SQLException ex){
                System.out.println(ex);
            }
        }catch(Exception ex){
            
        } 
        
        try{
            ti.registrarInspecciones(Double.parseDouble(txtPorcentajeAvance.getText()),
                    txtDescripcionInspeccion.getText(), String.valueOf(id_hi), dato);
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_btnRegistrarInspeccionMouseClicked

    private void btnRegistrarInspeccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarInspeccionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarInspeccionMouseEntered

    private void btnRegistrarInspeccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarInspeccionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarInspeccionMouseExited

    private void tblSeleccionarObra_RegInspeccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccionarObra_RegInspeccionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSeleccionarObra_RegInspeccionesMouseClicked

    private void txtDescripcionInspeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescripcionInspeccionMouseClicked
        // TODO add your handling code here:
        txtDescripcionInspeccion.setText("");
    }//GEN-LAST:event_txtDescripcionInspeccionMouseClicked

    private void txtPorcentajeAvanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPorcentajeAvanceMouseClicked
        // TODO add your handling code here:
        txtPorcentajeAvance.setText("");
    }//GEN-LAST:event_txtPorcentajeAvanceMouseClicked

    private void btnEliminarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarFuncionarioMouseClicked
        // TODO add your handling code here:
        btnIngresarFuncionario.setBackground(new Color (255,102,0));
        btnEditarFuncionario.setBackground(new Color (51,0,204));
        btnEliminarFuncionario.setBackground(new Color (255,153,255));
        btnListarFuncionario.setBackground(new Color (0,153,153));


        PanelMenuReuniones.setVisible(false);
        PanelRegistrarReunion.setVisible(false);
        PanelRegistrarInspeccion.setVisible(false);
        PanelReuniones.setVisible(true);
        PanelSeguimientoInspecciones.setVisible(false);

    }//GEN-LAST:event_btnEliminarFuncionarioMouseClicked

    private void btnListarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarFuncionarioMouseClicked
        // TODO add your handling code here:
        btnIngresarFuncionario.setBackground(new Color (255,102,0));
        btnEditarFuncionario.setBackground(new Color (51,0,204));
        btnEliminarFuncionario.setBackground(new Color (204,0,204));
        btnListarFuncionario.setBackground(new Color (0,204,153));


        PanelMenuReuniones.setVisible(false);
        PanelRegistrarReunion.setVisible(false);
        PanelRegistrarInspeccion.setVisible(false);
        PanelReuniones.setVisible(false);
        PanelSeguimientoInspecciones.setVisible(true);

    }//GEN-LAST:event_btnListarFuncionarioMouseClicked

    private void tblSeleccionarObra_Reunion_SeguimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccionarObra_Reunion_SeguimientoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSeleccionarObra_Reunion_SeguimientoMouseClicked

    private void tblSeguimientoReunionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeguimientoReunionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSeguimientoReunionesMouseClicked

    private void tblSeguimientoInspeccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeguimientoInspeccionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSeguimientoInspeccionesMouseClicked

    private void tblSeleccionarObra_InspeccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccionarObra_InspeccionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSeleccionarObra_InspeccionesMouseClicked

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen(); //para rescatar el valor X de la posición de la ventana
        int y = evt.getYOnScreen(); //para rescatar el valor Y de la posición de la ventana

        this.setLocation(x - xMouse ,y - yMouse);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FrameDragMouseClicked

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FrameDragMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Reuniones_Inspecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Reuniones_Inspecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Reuniones_Inspecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Reuniones_Inspecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Reuniones_Inspecciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Drag;
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JPanel PanelMenuReuniones;
    private javax.swing.JPanel PanelRegistrarInspeccion;
    private javax.swing.JPanel PanelRegistrarReunion;
    private javax.swing.JPanel PanelReuniones;
    private javax.swing.JPanel PanelSeguimientoInspecciones;
    private javax.swing.JLabel btnAtras_Fun;
    private javax.swing.JPanel btnEditarFuncionario;
    private javax.swing.JPanel btnEliminarFuncionario;
    private javax.swing.JPanel btnIngresarFuncionario;
    private javax.swing.JPanel btnLimpiarFun;
    private javax.swing.JPanel btnLimpiarInspeccion;
    private javax.swing.JPanel btnListarFuncionario;
    private javax.swing.JPanel btnRegistrarInspeccion;
    private javax.swing.JPanel btnRegistrarReunion;
    private javax.swing.JLabel btnSalir_Fun;
    private javax.swing.JComboBox<String> cmbHitoInspeccion;
    private javax.swing.JComboBox<String> cmbHitoReunion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTable tblSeguimientoInspecciones;
    private javax.swing.JTable tblSeguimientoReuniones;
    private javax.swing.JTable tblSeleccionarObra_Inspecciones;
    private javax.swing.JTable tblSeleccionarObra_RegInspecciones;
    private javax.swing.JTable tblSeleccionarObra_Reunion;
    private javax.swing.JTable tblSeleccionarObra_Reunion_Seguimiento;
    private javax.swing.JTextField txtDescripcionInspeccion;
    private javax.swing.JTextField txtFechaReunion;
    private javax.swing.JTextField txtHoraInicio;
    private javax.swing.JTextField txtHoraTermino;
    private javax.swing.JTextField txtInspector;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtNombreCitador;
    private javax.swing.JTextField txtPorcentajeAvance;
    // End of variables declaration//GEN-END:variables
}
