/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.Conexion;
import Modelo.Material;
import Modelo.Proyecto;
import Negocio.TProyecto;
import Negocio.TLogin;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esteban
 */
public class GUI_Proyectos extends javax.swing.JFrame {

    TLogin tLogin = new TLogin();
    /**
     * Creates new form GUI_Proyectos
     */
    String nombre;
    String descripcion;
    int xMouse;
    int yMouse; 
    
    public GUI_Proyectos() {
        initComponents();
        this.setLocationRelativeTo(null);
        muestraFecha();
        llenarTabla();
        jLabel3.setText(tLogin.getUsuario());
    }
    
    void muestraFecha(){
        //Muestra la fecha en el label
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat();
        lblDate.setText(s.format(d));
        /*Función para mostrar la fecha actual en el menú*/
    } 
        void llenarTabla(){
        Conexion con = new Conexion();
        try {
            con.getConexion();
            Statement stmt = con.getConexion().createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM proyecto");
            DefaultTableModel value = new DefaultTableModel();
            tblSeleccionarObra_Arriendo.setModel(value);
            value.addColumn("CODIGO PROYECTO");
            value.addColumn("NOMBRE PROYECTO");
            value.addColumn("DESCRIPCION PROYECTO");
            while(rs.next()){
               value.addRow(new Object[]{rs.getString("ID_PROY"), rs.getString("NOMBRE_PROY"),rs.getString("DESCRIPCION_PROY")});
            }
            rs.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir_Fun = new javax.swing.JLabel();
        btnAtras_Fun = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblDate = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        PanelMenuFuncionarios = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        PanelCrearProyecto = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnLimpiar_Proyecto = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtNombreProyecto = new javax.swing.JTextField();
        txtDescripcionProyecto = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnCrearProyecto = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        PanelEditarProyecto = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        txtCodEditarProyecto = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        btnEditarProyecto = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        btnLimpiarEditProyecto = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        btnBuscarProyecto_Edit = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtNombreProyecto_Edit = new javax.swing.JTextField();
        txtDescripcionProyecto_Edit = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        PanelEliminarProyecto = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        txtCodProyecto_Elim = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        btnEliminarProyecto = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        btnLimpiarElimProyecto = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        PanelListarProyectos = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSeleccionarObra_Arriendo = new javax.swing.JTable();
        PanelProyectosFun = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        txtCodigoProyecto_Hitos = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        btnBuscarProyecto_Hitos = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSubProcesos_Proyecto = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblHitosProyecto = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnProyectosFuncionario = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnIngresarFuncionario = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnEditarFuncionario = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnEliminarFuncionario = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnListarFuncionario = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Drag = new javax.swing.JPanel();
        FrameDrag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.CardLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 597, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 19, -1, -1));

        btnSalir_Fun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CERRAR_MINI_ICON.png"))); // NOI18N
        btnSalir_Fun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalir_FunMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir_Fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(966, 15, -1, -1));

        btnAtras_Fun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ATRAS_MINI_ICON.png"))); // NOI18N
        btnAtras_Fun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtras_FunMouseClicked(evt);
            }
        });
        jPanel1.add(btnAtras_Fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 15, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("USER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 19, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/USER_MINI_ICON_MAINMENU.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 23, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSTRUCTORA VIALIS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 14, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CALENDARIO_MINI_ICON_MAINMENU.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 23, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 54, 991, 13));

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("jLabel6");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 23, -1, -1));

        jPanel9.setBackground(new java.awt.Color(102, 102, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel9.setLayout(new java.awt.CardLayout());

        PanelMenuFuncionarios.setBackground(new java.awt.Color(102, 102, 255));
        PanelMenuFuncionarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelMenuFuncionarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("¡Bienvenido al menú de Proyectos!");
        PanelMenuFuncionarios.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 65, -1, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Utiliza diversas herramientas para el control y gestión de proyectos Vialis");
        PanelMenuFuncionarios.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 108, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Proyectos_MenuPrincipal.png"))); // NOI18N
        PanelMenuFuncionarios.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Funciones disponibles: ");
        PanelMenuFuncionarios.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 147, -1, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("1.- Generar Nuevo Proyecto");
        PanelMenuFuncionarios.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 174, -1, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("2.- Edición de Proyecto");
        PanelMenuFuncionarios.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 201, -1, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("4.- Listar Proyectos");
        PanelMenuFuncionarios.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 255, -1, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("3.- Eliminar Proyecto");
        PanelMenuFuncionarios.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 228, -1, -1));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("5.- Proyectos del Funcionario");
        PanelMenuFuncionarios.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 282, -1, -1));

        jPanel9.add(PanelMenuFuncionarios, "card7");

        PanelCrearProyecto.setBackground(new java.awt.Color(102, 102, 255));
        PanelCrearProyecto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelCrearProyecto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Crear Proyecto");
        PanelCrearProyecto.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nombre del Proyecto:");
        PanelCrearProyecto.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Descripción del Proyecto");
        PanelCrearProyecto.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        btnLimpiar_Proyecto.setBackground(new java.awt.Color(204, 51, 0));
        btnLimpiar_Proyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiar_ProyectoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiar_ProyectoMouseExited(evt);
            }
        });
        btnLimpiar_Proyecto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("LIMPIAR");
        btnLimpiar_Proyecto.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        PanelCrearProyecto.add(btnLimpiar_Proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 100, 50));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        PanelCrearProyecto.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 189, -1));

        txtNombreProyecto.setBackground(new java.awt.Color(102, 102, 255));
        txtNombreProyecto.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreProyecto.setText("Ingrese nombre aquí...");
        txtNombreProyecto.setBorder(null);
        txtNombreProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreProyectoMouseClicked(evt);
            }
        });
        PanelCrearProyecto.add(txtNombreProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 192, -1));

        txtDescripcionProyecto.setBackground(new java.awt.Color(102, 102, 255));
        txtDescripcionProyecto.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcionProyecto.setText("Ingrese la descripción...");
        txtDescripcionProyecto.setBorder(null);
        txtDescripcionProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDescripcionProyectoMouseClicked(evt);
            }
        });
        PanelCrearProyecto.add(txtDescripcionProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 189, -1));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        PanelCrearProyecto.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 192, -1));

        btnCrearProyecto.setBackground(new java.awt.Color(0, 153, 153));
        btnCrearProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearProyectoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearProyectoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearProyectoMouseExited(evt);
            }
        });
        btnCrearProyecto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("CREAR");
        btnCrearProyecto.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 13, -1, -1));

        PanelCrearProyecto.add(btnCrearProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 120, 50));

        jPanel9.add(PanelCrearProyecto, "card2");

        PanelEditarProyecto.setBackground(new java.awt.Color(102, 102, 255));
        PanelEditarProyecto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelEditarProyecto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Edición de Proyecto");
        PanelEditarProyecto.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Ingrese Código de Proyecto:");

        txtCodEditarProyecto.setBackground(new java.awt.Color(102, 102, 255));
        txtCodEditarProyecto.setForeground(new java.awt.Color(255, 255, 255));
        txtCodEditarProyecto.setText("Ingrese código...");
        txtCodEditarProyecto.setBorder(null);
        txtCodEditarProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodEditarProyectoMouseClicked(evt);
            }
        });

        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));

        btnEditarProyecto.setBackground(new java.awt.Color(0, 153, 153));
        btnEditarProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarProyectoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarProyectoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarProyectoMouseExited(evt);
            }
        });
        btnEditarProyecto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("EDITAR");
        btnEditarProyecto.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 13, -1, -1));

        btnLimpiarEditProyecto.setBackground(new java.awt.Color(204, 51, 0));
        btnLimpiarEditProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarEditProyectoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarEditProyectoMouseExited(evt);
            }
        });
        btnLimpiarEditProyecto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("LIMPIAR");
        btnLimpiarEditProyecto.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jSeparator12.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnBuscarProyecto_Edit.setBackground(new java.awt.Color(255, 204, 51));
        btnBuscarProyecto_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarProyecto_EditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarProyecto_EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarProyecto_EditMouseExited(evt);
            }
        });
        btnBuscarProyecto_Edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("BUSCAR");
        btnBuscarProyecto_Edit.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(txtCodEditarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnBuscarProyecto_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiarEditProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(5, 5, 5)
                        .addComponent(txtCodEditarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnLimpiarEditProyecto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarProyecto_Edit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(btnEditarProyecto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PanelEditarProyecto.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 740, 100));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nombre del Proyecto:");
        PanelEditarProyecto.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Descripción del Proyecto");
        PanelEditarProyecto.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        PanelEditarProyecto.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 189, -1));

        txtNombreProyecto_Edit.setBackground(new java.awt.Color(102, 102, 255));
        txtNombreProyecto_Edit.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreProyecto_Edit.setText("Busque un Proyecto...");
        txtNombreProyecto_Edit.setBorder(null);
        txtNombreProyecto_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreProyecto_EditMouseClicked(evt);
            }
        });
        PanelEditarProyecto.add(txtNombreProyecto_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 192, -1));

        txtDescripcionProyecto_Edit.setBackground(new java.awt.Color(102, 102, 255));
        txtDescripcionProyecto_Edit.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcionProyecto_Edit.setText("Busque un Proyecto...");
        txtDescripcionProyecto_Edit.setBorder(null);
        txtDescripcionProyecto_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDescripcionProyecto_EditMouseClicked(evt);
            }
        });
        PanelEditarProyecto.add(txtDescripcionProyecto_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 189, -1));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        PanelEditarProyecto.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 192, -1));

        jPanel9.add(PanelEditarProyecto, "card2");

        PanelEliminarProyecto.setBackground(new java.awt.Color(102, 102, 255));
        PanelEliminarProyecto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBackground(new java.awt.Color(102, 102, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Ingrese Código del Proyecto");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtCodProyecto_Elim.setBackground(new java.awt.Color(102, 102, 255));
        txtCodProyecto_Elim.setForeground(new java.awt.Color(255, 255, 255));
        txtCodProyecto_Elim.setText("Ingrese código aquí...");
        txtCodProyecto_Elim.setBorder(null);
        txtCodProyecto_Elim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodProyecto_ElimMouseClicked(evt);
            }
        });
        jPanel6.add(txtCodProyecto_Elim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 380, -1));

        jSeparator21.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 380, 10));

        btnEliminarProyecto.setBackground(new java.awt.Color(0, 153, 153));
        btnEliminarProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarProyectoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarProyectoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarProyectoMouseExited(evt);
            }
        });
        btnEliminarProyecto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("ELIMINAR");
        btnEliminarProyecto.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 13, -1, -1));

        jPanel6.add(btnEliminarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 150, 50));

        btnLimpiarElimProyecto.setBackground(new java.awt.Color(204, 51, 0));
        btnLimpiarElimProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarElimProyectoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarElimProyectoMouseExited(evt);
            }
        });
        btnLimpiarElimProyecto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("LIMPIAR");
        btnLimpiarElimProyecto.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jPanel6.add(btnLimpiarElimProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 100, 50));

        jLabel49.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Eliminar Proyecto");

        javax.swing.GroupLayout PanelEliminarProyectoLayout = new javax.swing.GroupLayout(PanelEliminarProyecto);
        PanelEliminarProyecto.setLayout(PanelEliminarProyectoLayout);
        PanelEliminarProyectoLayout.setHorizontalGroup(
            PanelEliminarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEliminarProyectoLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addGroup(PanelEliminarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        PanelEliminarProyectoLayout.setVerticalGroup(
            PanelEliminarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEliminarProyectoLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel49)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jPanel9.add(PanelEliminarProyecto, "card4");

        PanelListarProyectos.setBackground(new java.awt.Color(102, 102, 255));
        PanelListarProyectos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelListarProyectos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Listado de Proyectos");
        PanelListarProyectos.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(null);
        jScrollPane4.setForeground(new java.awt.Color(255, 255, 255));

        tblSeleccionarObra_Arriendo.setBackground(new java.awt.Color(252, 251, 251));
        tblSeleccionarObra_Arriendo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSeleccionarObra_Arriendo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Puente Cau Cau"},
                {"Castillo Ratinbum"},
                {"Centro Pokémon"},
                {"Acuario de Jureles"}
            },
            new String [] {
                "NOMBRE DE OBRA"
            }
        ));
        tblSeleccionarObra_Arriendo.setGridColor(new java.awt.Color(255, 255, 255));
        tblSeleccionarObra_Arriendo.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSeleccionarObra_Arriendo.setShowHorizontalLines(false);
        tblSeleccionarObra_Arriendo.setShowVerticalLines(false);
        tblSeleccionarObra_Arriendo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccionarObra_ArriendoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblSeleccionarObra_Arriendo);

        PanelListarProyectos.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 760, 280));

        jPanel9.add(PanelListarProyectos, "card5");

        PanelProyectosFun.setBackground(new java.awt.Color(102, 102, 255));
        PanelProyectosFun.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelProyectosFun.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(102, 102, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Ingrese Código de Proyecto:");
        jPanel7.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtCodigoProyecto_Hitos.setBackground(new java.awt.Color(102, 102, 255));
        txtCodigoProyecto_Hitos.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoProyecto_Hitos.setText("Ingrese el código aquí...");
        txtCodigoProyecto_Hitos.setBorder(null);
        txtCodigoProyecto_Hitos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoProyecto_HitosMouseClicked(evt);
            }
        });
        jPanel7.add(txtCodigoProyecto_Hitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, -1));

        jSeparator22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 250, 10));

        btnBuscarProyecto_Hitos.setBackground(new java.awt.Color(255, 204, 51));
        btnBuscarProyecto_Hitos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarProyecto_HitosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarProyecto_HitosMouseExited(evt);
            }
        });
        btnBuscarProyecto_Hitos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("BUSCAR");
        btnBuscarProyecto_Hitos.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 13, -1, -1));

        jPanel7.add(btnBuscarProyecto_Hitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 120, 50));

        PanelProyectosFun.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 430, 100));

        jLabel51.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Hitos de Proyecto");
        PanelProyectosFun.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setBorder(null);
        jScrollPane6.setForeground(new java.awt.Color(255, 255, 255));

        tblSubProcesos_Proyecto.setBackground(new java.awt.Color(252, 251, 251));
        tblSubProcesos_Proyecto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSubProcesos_Proyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "Seleccione Un Hito", "Seleccione un Hito", "0", "0"}
            },
            new String [] {
                "ID", "SUBPROCESO", "FECHA INGRESO", "AVANCE", "ESTADO"
            }
        ));
        tblSubProcesos_Proyecto.setGridColor(new java.awt.Color(255, 255, 255));
        tblSubProcesos_Proyecto.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSubProcesos_Proyecto.setShowHorizontalLines(false);
        tblSubProcesos_Proyecto.setShowVerticalLines(false);
        tblSubProcesos_Proyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSubProcesos_ProyectoMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblSubProcesos_Proyecto);

        PanelProyectosFun.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 760, 150));

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane7.setBorder(null);
        jScrollPane7.setForeground(new java.awt.Color(255, 255, 255));

        tblHitosProyecto.setBackground(new java.awt.Color(252, 251, 251));
        tblHitosProyecto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblHitosProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Inicio Obra", "25/06/2017", "50%", "Incompleto"},
                {"2", "Arquitectura", "28/06/2017", "30%", "Incompleto"},
                {"3", "Organización de Trabajo", "29/08/2017", "50%", "Incompleto"},
                {"4", "Compra de Materiales", "04/11/2017", "100%", "Completo"}
            },
            new String [] {
                "ID", "HITO", "FECHA INGRESO", "AVANCE", "ESTADO"
            }
        ));
        tblHitosProyecto.setGridColor(new java.awt.Color(255, 255, 255));
        tblHitosProyecto.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblHitosProyecto.setShowHorizontalLines(false);
        tblHitosProyecto.setShowVerticalLines(false);
        tblHitosProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHitosProyectoMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblHitosProyecto);

        PanelProyectosFun.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 760, 110));

        jPanel9.add(PanelProyectosFun, "card6");

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 217, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProyectosFuncionario.setBackground(new java.awt.Color(204, 0, 0));
        btnProyectosFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProyectosFuncionarioMouseClicked(evt);
            }
        });
        btnProyectosFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Seguimiento");
        btnProyectosFuncionario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SeguimientoProyecto_Proyectos.png"))); // NOI18N
        btnProyectosFuncionario.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 20, 70, -1));

        jPanel3.add(btnProyectosFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 140, 130));

        btnIngresarFuncionario.setBackground(new java.awt.Color(255, 102, 0));
        btnIngresarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarFuncionarioMouseClicked(evt);
            }
        });
        btnIngresarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Crear Proyecto");
        btnIngresarFuncionario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Proyectos_NuevoProyecto.png"))); // NOI18N
        btnIngresarFuncionario.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel3.add(btnIngresarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 130));

        btnEditarFuncionario.setBackground(new java.awt.Color(51, 0, 204));
        btnEditarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarFuncionarioMouseClicked(evt);
            }
        });
        btnEditarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Editar");
        btnEditarFuncionario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edicion.png"))); // NOI18N
        btnEditarFuncionario.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 20, 70, -1));

        jPanel3.add(btnEditarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 140, 130));

        btnEliminarFuncionario.setBackground(new java.awt.Color(204, 0, 204));
        btnEliminarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarFuncionarioMouseClicked(evt);
            }
        });
        btnEliminarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Eliminar");
        btnEliminarFuncionario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ELIMINAR.png"))); // NOI18N
        btnEliminarFuncionario.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 20, 70, -1));

        jPanel3.add(btnEliminarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 140, 130));

        btnListarFuncionario.setBackground(new java.awt.Color(0, 153, 153));
        btnListarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarFuncionarioMouseClicked(evt);
            }
        });
        btnListarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Listar");
        btnListarFuncionario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Listar.png"))); // NOI18N
        btnListarFuncionario.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 70));

        jPanel3.add(btnListarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 140, 130));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 80, -1, -1));

        Drag.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout DragLayout = new javax.swing.GroupLayout(Drag);
        Drag.setLayout(DragLayout);
        DragLayout.setHorizontalGroup(
            DragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        DragLayout.setVerticalGroup(
            DragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(Drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 60));

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FrameDragMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        jPanel1.add(FrameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalir_FunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir_FunMouseClicked
        // TODO add your handling code here:
        new Mensajes_SalirAp().setVisible(true);
    }//GEN-LAST:event_btnSalir_FunMouseClicked

    private void btnAtras_FunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtras_FunMouseClicked
        // TODO add your handling code here:
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtras_FunMouseClicked

    private void btnLimpiar_ProyectoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiar_ProyectoMouseEntered
        // TODO add your handling code here:
        btnLimpiar_Proyecto.setBackground(new Color (255,51,0));
    }//GEN-LAST:event_btnLimpiar_ProyectoMouseEntered

    private void btnLimpiar_ProyectoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiar_ProyectoMouseExited
        // TODO add your handling code here:
        btnLimpiar_Proyecto.setBackground(new Color (204,51,0));
    }//GEN-LAST:event_btnLimpiar_ProyectoMouseExited

    private void btnCrearProyectoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearProyectoMouseEntered
        // TODO add your handling code here:
        btnCrearProyecto.setBackground(new Color (0,204,153));
    }//GEN-LAST:event_btnCrearProyectoMouseEntered

    private void btnCrearProyectoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearProyectoMouseExited
        // TODO add your handling code here:
        btnCrearProyecto.setBackground(new Color (0,153,153));
    }//GEN-LAST:event_btnCrearProyectoMouseExited

    private void btnEditarProyectoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarProyectoMouseEntered
        // TODO add your handling code here:
        btnEditarProyecto.setBackground(new Color (0,204,153));
    }//GEN-LAST:event_btnEditarProyectoMouseEntered

    private void btnEditarProyectoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarProyectoMouseExited
        // TODO add your handling code here:
        btnEditarProyecto.setBackground(new Color (0,153,153));
    }//GEN-LAST:event_btnEditarProyectoMouseExited

    private void btnLimpiarEditProyectoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarEditProyectoMouseEntered
        // TODO add your handling code here:
        btnLimpiarEditProyecto.setBackground(new Color (255,51,0));
    }//GEN-LAST:event_btnLimpiarEditProyectoMouseEntered

    private void btnLimpiarEditProyectoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarEditProyectoMouseExited
        // TODO add your handling code here:
        btnLimpiarEditProyecto.setBackground(new Color (204,51,0));
    }//GEN-LAST:event_btnLimpiarEditProyectoMouseExited

    private void btnBuscarProyecto_EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProyecto_EditMouseEntered
        // TODO add your handling code here:
        btnBuscarProyecto_Edit.setBackground(new Color (255,204,153));
    }//GEN-LAST:event_btnBuscarProyecto_EditMouseEntered

    private void btnBuscarProyecto_EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProyecto_EditMouseExited
        // TODO add your handling code here:
        btnBuscarProyecto_Edit.setBackground(new Color (255,204,51));
    }//GEN-LAST:event_btnBuscarProyecto_EditMouseExited

    private void btnEliminarProyectoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProyectoMouseEntered
        // TODO add your handling code here:
        btnEliminarProyecto.setBackground(new Color (0,204,153));
    }//GEN-LAST:event_btnEliminarProyectoMouseEntered

    private void btnEliminarProyectoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProyectoMouseExited
        // TODO add your handling code here:
        btnEliminarProyecto.setBackground(new Color (0,153,153));
    }//GEN-LAST:event_btnEliminarProyectoMouseExited

    private void btnLimpiarElimProyectoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarElimProyectoMouseEntered
        // TODO add your handling code here:
        btnLimpiarElimProyecto.setBackground(new Color (255,51,0));
    }//GEN-LAST:event_btnLimpiarElimProyectoMouseEntered

    private void btnLimpiarElimProyectoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarElimProyectoMouseExited
        // TODO add your handling code here:
        btnLimpiarElimProyecto.setBackground(new Color (204,51,0));
    }//GEN-LAST:event_btnLimpiarElimProyectoMouseExited

    private void btnBuscarProyecto_HitosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProyecto_HitosMouseEntered
        // TODO add your handling code here:
        btnBuscarProyecto_Hitos.setBackground(new Color (255,204,153));
    }//GEN-LAST:event_btnBuscarProyecto_HitosMouseEntered

    private void btnBuscarProyecto_HitosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProyecto_HitosMouseExited
        // TODO add your handling code here:
        btnBuscarProyecto_Hitos.setBackground(new Color (255,204,51));
    }//GEN-LAST:event_btnBuscarProyecto_HitosMouseExited

    private void btnProyectosFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProyectosFuncionarioMouseClicked
        // TODO add your handling code here:
        btnIngresarFuncionario.setBackground(new Color (255,102,0));
        btnEditarFuncionario.setBackground(new Color (51,0,204));
        btnEliminarFuncionario.setBackground(new Color (204,0,204));
        btnListarFuncionario.setBackground(new Color (0,153,153));
        btnProyectosFuncionario.setBackground(new Color (255,102,102));

        PanelMenuFuncionarios.setVisible(false);
        PanelCrearProyecto.setVisible(false);
        PanelEditarProyecto.setVisible(false);
        PanelEliminarProyecto.setVisible(false);
        PanelListarProyectos.setVisible(false);
        PanelProyectosFun.setVisible(true);
    }//GEN-LAST:event_btnProyectosFuncionarioMouseClicked

    private void btnIngresarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarFuncionarioMouseClicked
        // TODO add your handling code here:

        btnIngresarFuncionario.setBackground(new Color (255,204,153));
        btnEditarFuncionario.setBackground(new Color (51,0,204));
        btnEliminarFuncionario.setBackground(new Color (204,0,204));
        btnListarFuncionario.setBackground(new Color (0,153,153));
        btnProyectosFuncionario.setBackground(new Color (204,0,0));

        PanelMenuFuncionarios.setVisible(false);
        PanelCrearProyecto.setVisible(true);
        PanelEditarProyecto.setVisible(false);
        PanelEliminarProyecto.setVisible(false);
        PanelListarProyectos.setVisible(false);
        PanelProyectosFun.setVisible(false);
    }//GEN-LAST:event_btnIngresarFuncionarioMouseClicked

    private void btnEditarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarFuncionarioMouseClicked
        // TODO add your handling code here:
        btnIngresarFuncionario.setBackground(new Color (255,102,0));
        btnEditarFuncionario.setBackground(new Color (204,204,255));
        btnEliminarFuncionario.setBackground(new Color (204,0,204));
        btnListarFuncionario.setBackground(new Color (0,153,153));
        btnProyectosFuncionario.setBackground(new Color (204,0,0));

        PanelMenuFuncionarios.setVisible(false);
        PanelCrearProyecto.setVisible(false);
        PanelEditarProyecto.setVisible(true);
        PanelEliminarProyecto.setVisible(false);
        PanelListarProyectos.setVisible(false);
        PanelProyectosFun.setVisible(false);
    }//GEN-LAST:event_btnEditarFuncionarioMouseClicked

    private void btnEliminarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarFuncionarioMouseClicked
        // TODO add your handling code here:
        btnIngresarFuncionario.setBackground(new Color (255,102,0));
        btnEditarFuncionario.setBackground(new Color (51,0,204));
        btnEliminarFuncionario.setBackground(new Color (255,153,255));
        btnListarFuncionario.setBackground(new Color (0,153,153));
        btnProyectosFuncionario.setBackground(new Color (204,0,0));

        PanelMenuFuncionarios.setVisible(false);
        PanelCrearProyecto.setVisible(false);
        PanelEditarProyecto.setVisible(false);
        PanelEliminarProyecto.setVisible(true);
        PanelListarProyectos.setVisible(false);
        PanelProyectosFun.setVisible(false);
    }//GEN-LAST:event_btnEliminarFuncionarioMouseClicked

    private void btnListarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarFuncionarioMouseClicked
        btnIngresarFuncionario.setBackground(new Color (255,102,0));
        btnEditarFuncionario.setBackground(new Color (51,0,204));
        btnEliminarFuncionario.setBackground(new Color (204,0,204));
        btnListarFuncionario.setBackground(new Color (0,204,153));
        btnProyectosFuncionario.setBackground(new Color (204,0,0));

        PanelMenuFuncionarios.setVisible(false);
        PanelCrearProyecto.setVisible(false);
        PanelEditarProyecto.setVisible(false);
        PanelEliminarProyecto.setVisible(false);
        PanelListarProyectos.setVisible(true);
        PanelProyectosFun.setVisible(false);
        
        llenarTabla();
        

    }//GEN-LAST:event_btnListarFuncionarioMouseClicked

    private void tblSeleccionarObra_ArriendoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccionarObra_ArriendoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSeleccionarObra_ArriendoMouseClicked

    private void tblSubProcesos_ProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSubProcesos_ProyectoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSubProcesos_ProyectoMouseClicked

    private void tblHitosProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHitosProyectoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHitosProyectoMouseClicked

    private void btnCrearProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearProyectoMouseClicked
        TProyecto rp = new TProyecto();
        try{
             rp.registrarProyecto(txtNombreProyecto.getText(), txtDescripcionProyecto.getText());
             new Mensajes_ExitoIngreso().setVisible(true);
        }catch(Exception ex){
            new Mensajes_ErrorIngresar().setVisible(true);   
        }
        
    }//GEN-LAST:event_btnCrearProyectoMouseClicked

    private void btnEliminarProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProyectoMouseClicked
        TProyecto rp = new TProyecto();
        try{
            rp.eliminarProyecto(txtCodProyecto_Elim.getText());
            new Mensajes_ExitoEliminar().setVisible(true);          
        }catch(Exception ex){
            new Mensajes_ErrorEliminar().setVisible(true);
        }
        
    }//GEN-LAST:event_btnEliminarProyectoMouseClicked

    private void btnBuscarProyecto_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProyecto_EditMouseClicked
        
        Conexion con = new Conexion();
        
        try{
            con.getConexion();
            Statement stmt = con.getConexion().createStatement();
            try{
                ResultSet rs = stmt.executeQuery("SELECT * FROM PROYECTO WHERE ID_PROY ='"+txtCodEditarProyecto.getText()+"'");
                while(rs.next()){
                    txtNombreProyecto_Edit.setText(rs.getString("NOMBRE_PROY"));
                    txtDescripcionProyecto_Edit.setText(rs.getString("DESCRIPCION_PROY"));
                }
            }catch (SQLException ex){
                System.out.println(ex);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        

        
    }//GEN-LAST:event_btnBuscarProyecto_EditMouseClicked

    private void btnEditarProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarProyectoMouseClicked
        TProyecto rp = new TProyecto();
        try{
             rp.editarProyecto(txtNombreProyecto_Edit.getText(), txtDescripcionProyecto_Edit.getText(), txtCodEditarProyecto.getText());
             new Mensajes_ExitoModificacion().setVisible(true);
        }catch(Exception ex){
            new Mensajes_ExitoModificacion().setVisible(true);
        }
    }//GEN-LAST:event_btnEditarProyectoMouseClicked

    private void txtNombreProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProyectoMouseClicked
        // TODO add your handling code here:
        txtNombreProyecto.setText("");
    }//GEN-LAST:event_txtNombreProyectoMouseClicked

    private void txtDescripcionProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescripcionProyectoMouseClicked
        // TODO add your handling code here:
        txtDescripcionProyecto.setText("");
    }//GEN-LAST:event_txtDescripcionProyectoMouseClicked

    private void txtCodEditarProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodEditarProyectoMouseClicked
        // TODO add your handling code here:
        txtCodEditarProyecto.setText("");
    }//GEN-LAST:event_txtCodEditarProyectoMouseClicked

    private void txtNombreProyecto_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProyecto_EditMouseClicked
        // TODO add your handling code here:
        txtNombreProyecto_Edit.setText("");
    }//GEN-LAST:event_txtNombreProyecto_EditMouseClicked

    private void txtDescripcionProyecto_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescripcionProyecto_EditMouseClicked
        // TODO add your handling code here:
        txtDescripcionProyecto_Edit.setText("");
    }//GEN-LAST:event_txtDescripcionProyecto_EditMouseClicked

    private void txtCodProyecto_ElimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodProyecto_ElimMouseClicked
        // TODO add your handling code here:
        txtCodProyecto_Elim.setText("");
    }//GEN-LAST:event_txtCodProyecto_ElimMouseClicked

    private void txtCodigoProyecto_HitosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoProyecto_HitosMouseClicked
        // TODO add your handling code here:
        txtCodigoProyecto_Hitos.setText("");
    }//GEN-LAST:event_txtCodigoProyecto_HitosMouseClicked

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen(); //para rescatar el valor X de la posición de la ventana
        int y = evt.getYOnScreen(); //para rescatar el valor Y de la posición de la ventana

        this.setLocation(x - xMouse ,y - yMouse);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FrameDragMouseClicked

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FrameDragMousePressed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Proyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Proyectos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Drag;
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JPanel PanelCrearProyecto;
    private javax.swing.JPanel PanelEditarProyecto;
    private javax.swing.JPanel PanelEliminarProyecto;
    private javax.swing.JPanel PanelListarProyectos;
    private javax.swing.JPanel PanelMenuFuncionarios;
    private javax.swing.JPanel PanelProyectosFun;
    private javax.swing.JLabel btnAtras_Fun;
    private javax.swing.JPanel btnBuscarProyecto_Edit;
    private javax.swing.JPanel btnBuscarProyecto_Hitos;
    private javax.swing.JPanel btnCrearProyecto;
    private javax.swing.JPanel btnEditarFuncionario;
    private javax.swing.JPanel btnEditarProyecto;
    private javax.swing.JPanel btnEliminarFuncionario;
    private javax.swing.JPanel btnEliminarProyecto;
    private javax.swing.JPanel btnIngresarFuncionario;
    private javax.swing.JPanel btnLimpiarEditProyecto;
    private javax.swing.JPanel btnLimpiarElimProyecto;
    private javax.swing.JPanel btnLimpiar_Proyecto;
    private javax.swing.JPanel btnListarFuncionario;
    private javax.swing.JPanel btnProyectosFuncionario;
    private javax.swing.JLabel btnSalir_Fun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTable tblHitosProyecto;
    private javax.swing.JTable tblSeleccionarObra_Arriendo;
    private javax.swing.JTable tblSubProcesos_Proyecto;
    private javax.swing.JTextField txtCodEditarProyecto;
    private javax.swing.JTextField txtCodProyecto_Elim;
    private javax.swing.JTextField txtCodigoProyecto_Hitos;
    private javax.swing.JTextField txtDescripcionProyecto;
    private javax.swing.JTextField txtDescripcionProyecto_Edit;
    private javax.swing.JTextField txtNombreProyecto;
    private javax.swing.JTextField txtNombreProyecto_Edit;
    // End of variables declaration//GEN-END:variables
}
