/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.Conexion;
import Modelo.Maqui_Herra;
import Negocio.TArriendo;
import Negocio.TLogin;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class GUI_ArriendoHerramienta extends javax.swing.JFrame {

        TLogin tLogin = new TLogin();
   
    public GUI_ArriendoHerramienta() {
        initComponents();
        muestraFecha();
        llenar_cmbHerramientas();
        llenar_tblSeleccionarObra_Arriendo();
        jLabel3.setText(tLogin.getUsuario());
    }
    
    void muestraFecha(){
        //Muestra la fecha en el label
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat();
        lblDate.setText(s.format(d));
        /*Función para mostrar la fecha actual en el menú*/
    }
    
    void llenar_cmbHerramientas(){
        Conexion con = new Conexion();
        try{
            con.getConexion();
            Statement stmt = con.getConexion().createStatement();
            try(ResultSet rs = stmt.executeQuery("SELECT * FROM MAQUI_HERRA")){
                DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
                modeloCombo.addElement("Seleccionar");
                cmbHerramientas.setModel(modeloCombo);
                while(rs.next()){
                   // Maqui_Herra mh = new Maqui_Herra(rs.getString("NOMBRE_MH"));
                    modeloCombo.addElement(rs.getString("NOMBRE_MH"));
                    cmbHerramientas.setModel(modeloCombo);
                }               
                
            }
            
        }catch (SQLException e) {
            System.out.println(e);
        }
    }
    
    void llenar_tblSeleccionarObra_Arriendo(){
        Conexion con = new Conexion();
        try{
            con.getConexion();
            Statement stmt = con.getConexion().createStatement();
            try(ResultSet rs = stmt.executeQuery("SELECT * FROM PROYECTO")){
                DefaultTableModel modeloTabla = new DefaultTableModel();
                tblSeleccionarObra_Arriendo.setModel(modeloTabla);
                modeloTabla.addColumn("ID");
                modeloTabla.addColumn("NOMBRE");                
                while(rs.next()){
                   modeloTabla.addRow(new Object[]{ rs.getString("ID_PROY"),rs.getString("NOMBRE_PROY")});
                }               
                
            }
            
        }catch (SQLException e) {
            System.out.println(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        lblDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir_Fun = new javax.swing.JLabel();
        btnAtras_Fun = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbHerramientas = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSeleccionarObra_Arriendo = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        txtValorArriendo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtDisponibilidadArriendo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnArrendarHer = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        btnLimpiarHerramienta = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        txtFechaArriendo = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        txtFechaEntrega_Arriendo = new javax.swing.JTextField();
        txtCantidadHerramienta = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 66, 730, 10));

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("jLabel6");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 32, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 28, -1, -1));

        btnSalir_Fun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CERRAR_MINI_ICON.png"))); // NOI18N
        btnSalir_Fun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalir_FunMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir_Fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        btnAtras_Fun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ATRAS_MINI_ICON.png"))); // NOI18N
        btnAtras_Fun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtras_FunMouseClicked(evt);
            }
        });
        jPanel1.add(btnAtras_Fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("USER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 28, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/USER_MINI_ICON_MAINMENU.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 32, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSTRUCTORA VIALIS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 23, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CALENDARIO_MINI_ICON_MAINMENU.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 32, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Arriendo Herramientas");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha de Entrega");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        cmbHerramientas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbHerramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHerramientasActionPerformed(evt);
            }
        });
        jPanel1.add(cmbHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 190, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Seleccione Herramienta");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(null);
        jScrollPane4.setForeground(new java.awt.Color(255, 255, 255));

        tblSeleccionarObra_Arriendo.setBackground(new java.awt.Color(252, 251, 251));
        tblSeleccionarObra_Arriendo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSeleccionarObra_Arriendo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Puente Cau Cau"},
                {"Castillo Ratinbum"},
                {"Centro Pokémon"},
                {"Acuario de Jureles"}
            },
            new String [] {
                "NOMBRE DE OBRA"
            }
        ));
        tblSeleccionarObra_Arriendo.setGridColor(new java.awt.Color(255, 255, 255));
        tblSeleccionarObra_Arriendo.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSeleccionarObra_Arriendo.setShowHorizontalLines(false);
        tblSeleccionarObra_Arriendo.setShowVerticalLines(false);
        tblSeleccionarObra_Arriendo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccionarObra_ArriendoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblSeleccionarObra_Arriendo);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 360, 130));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Valor Arriendo");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 180, -1));

        txtValorArriendo.setEditable(false);
        txtValorArriendo.setBackground(new java.awt.Color(204, 204, 204));
        txtValorArriendo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtValorArriendo.setForeground(new java.awt.Color(204, 0, 0));
        txtValorArriendo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(txtValorArriendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 360, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Seleccione una obra...");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 180, -1));

        txtDisponibilidadArriendo.setEditable(false);
        txtDisponibilidadArriendo.setBackground(new java.awt.Color(204, 204, 204));
        txtDisponibilidadArriendo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDisponibilidadArriendo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(txtDisponibilidadArriendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 110, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("¿Disponibilidad?");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fecha de Arriendo");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        btnArrendarHer.setBackground(new java.awt.Color(0, 153, 153));
        btnArrendarHer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArrendarHerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArrendarHerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnArrendarHerMouseExited(evt);
            }
        });
        btnArrendarHer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("ARRENDAR");
        btnArrendarHer.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(btnArrendarHer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 120, 50));

        btnLimpiarHerramienta.setBackground(new java.awt.Color(204, 51, 0));
        btnLimpiarHerramienta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarHerramientaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarHerramientaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarHerramientaMouseExited(evt);
            }
        });
        btnLimpiarHerramienta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("LIMPIAR");
        btnLimpiarHerramienta.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(btnLimpiarHerramienta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 100, 50));

        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 230, 10));

        txtFechaArriendo.setBackground(new java.awt.Color(102, 102, 255));
        txtFechaArriendo.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaArriendo.setText("MM/DD/AAAA...");
        txtFechaArriendo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtFechaArriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaArriendoActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaArriendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 192, -1));

        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 230, 10));

        txtFechaEntrega_Arriendo.setBackground(new java.awt.Color(102, 102, 255));
        txtFechaEntrega_Arriendo.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaEntrega_Arriendo.setText("MM/DD/AAAA...");
        txtFechaEntrega_Arriendo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txtFechaEntrega_Arriendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 192, -1));

        txtCantidadHerramienta.setBackground(new java.awt.Color(102, 102, 255));
        txtCantidadHerramienta.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidadHerramienta.setText("Ingrese cantidad...");
        txtCantidadHerramienta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txtCantidadHerramienta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 192, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cantidad");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 230, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalir_FunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir_FunMouseClicked
        // TODO add your handling code here:
        new Mensajes_SalirAp().setVisible(true);
    }//GEN-LAST:event_btnSalir_FunMouseClicked

    private void btnAtras_FunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtras_FunMouseClicked
        // TODO add your handling code here:
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtras_FunMouseClicked

    private void tblSeleccionarObra_ArriendoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccionarObra_ArriendoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSeleccionarObra_ArriendoMouseClicked

    private void btnArrendarHerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArrendarHerMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArrendarHerMouseEntered

    private void btnArrendarHerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArrendarHerMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArrendarHerMouseExited

    private void btnLimpiarHerramientaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarHerramientaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarHerramientaMouseEntered

    private void btnLimpiarHerramientaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarHerramientaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarHerramientaMouseExited

    private void cmbHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHerramientasActionPerformed
        // TODO add your handling code here:
        
        Conexion con = new Conexion();
        try{
            con.getConexion();
            Statement stmt = con.getConexion().createStatement();
            try{
                ResultSet rs = stmt.executeQuery("SELECT DISPONIBILIDAD_MH, PRECIO_MH FROM MAQUI_HERRA WHERE NOMBRE_MH ='"+cmbHerramientas.getSelectedItem().toString()+"'");
                //int cantidad = (Integer)rs.getObject(1);
                while(rs.next()){
                    txtDisponibilidadArriendo.setText((String) rs.getString("DISPONIBILIDAD_MH"));
                    txtValorArriendo.setText((String) rs.getString("PRECIO_MH"));
                }                
            }catch (SQLException ex){
                System.out.println(ex);
            }
        }   catch (SQLException ex) {
                System.out.println(ex);
            }
        
    }//GEN-LAST:event_cmbHerramientasActionPerformed

    private void btnArrendarHerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArrendarHerMouseClicked
        // TODO add your handling code here:
        
        TArriendo arr = new TArriendo();
        DefaultTableModel modeloTabla = (DefaultTableModel)tblSeleccionarObra_Arriendo.getModel();
        String dato = String.valueOf(modeloTabla.getValueAt(tblSeleccionarObra_Arriendo.getSelectedRow(),0));
        int id_mh = 0;
        int disponible = Integer.parseInt(txtDisponibilidadArriendo.getText());
        int cantidad = Integer.parseInt(txtCantidadHerramienta.getText());
        
        Conexion con = new Conexion();
        try{
            con.getConexion();
            Statement stmt = con.getConexion().createStatement();
            try{
                ResultSet rs = stmt.executeQuery("SELECT ID_MH FROM MAQUI_HERRA WHERE NOMBRE_MH ='"+cmbHerramientas.getSelectedItem().toString()+"'");
                while(rs.next()){
                    String id = rs.getString("ID_MH");
                    id_mh = Integer.parseInt(id);
                }                
            }catch (SQLException ex){
                System.out.println(ex);
            }
        }   catch (SQLException ex) {
                System.out.println(ex);
            }
        
            try {
                if ((disponible - cantidad) < 0) {
                    JOptionPane.showMessageDialog(null, "Error","Cantidad solicitada excede al stock disponible" , 1);
                } else {
                    arr.registrarArriendo(txtFechaArriendo.getText(), txtFechaEntrega_Arriendo.getText(), id_mh, dato, cantidad);
                    JOptionPane.showMessageDialog(null, "Exito","Registro Exitoso" , 1);
            }                
            } catch (ParseException ex) {
                Logger.getLogger(GUI_ArriendoHerramienta.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error","Error al Registrar" , 1);
            }
        
        
        
    }//GEN-LAST:event_btnArrendarHerMouseClicked

    private void btnLimpiarHerramientaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarHerramientaMouseClicked
        txtFechaArriendo.setText("");
        txtFechaEntrega_Arriendo.setText("");
        txtDisponibilidadArriendo.setText("");
        txtValorArriendo.setText("");
        cmbHerramientas.setSelectedIndex(0);
        
        
      
    }//GEN-LAST:event_btnLimpiarHerramientaMouseClicked

    private void txtFechaArriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaArriendoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaArriendoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ArriendoHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ArriendoHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ArriendoHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ArriendoHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ArriendoHerramienta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnArrendarHer;
    private javax.swing.JLabel btnAtras_Fun;
    private javax.swing.JPanel btnLimpiarHerramienta;
    private javax.swing.JLabel btnSalir_Fun;
    private javax.swing.JComboBox<String> cmbHerramientas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTable tblSeleccionarObra_Arriendo;
    private javax.swing.JTextField txtCantidadHerramienta;
    private javax.swing.JTextField txtDisponibilidadArriendo;
    private javax.swing.JTextField txtFechaArriendo;
    private javax.swing.JTextField txtFechaEntrega_Arriendo;
    private javax.swing.JTextField txtValorArriendo;
    // End of variables declaration//GEN-END:variables
}
