/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.Conexion;
import Negocio.HitosConsultas;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esteban
 */
public class GUI_Hitos extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Inspecciones
     */
    int xMouse;
    int yMouse;
    Conexion con = new Conexion();
    public GUI_Hitos() {
        initComponents();
        this.setLocationRelativeTo(null);
        llenarObra();
        llenarObraTarea();
        llenarObraSeguimiento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir_Fun = new javax.swing.JLabel();
        btnAtras_Fun = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblDate = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        PanelMenuActividades = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        PanelRegistrarHito = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtNombreHito1 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        btnRegistrarInspeccion1 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblSeleccionarObra_RegHito1 = new javax.swing.JTable();
        PanelRegistrarActividades = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtNombreTarea = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btnRegistrarTarea = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        txtFechaInicioTarea = new javax.swing.JTextField();
        jSeparator31 = new javax.swing.JSeparator();
        jLabel73 = new javax.swing.JLabel();
        txtFechaTerminoTarea = new javax.swing.JTextField();
        jSeparator34 = new javax.swing.JSeparator();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblSeleccionarObra_Tarea = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tblSeleccioneHito_Tareas = new javax.swing.JTable();
        PanelSeguimiento = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSeleccionarObra_Seguimiento_Tareas = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblSeleccioneTarea_Seguimiento = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblSeleccioneHito_Seguimiento = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        txtTareaSeleccionada = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        txtPorcentajeAvance = new javax.swing.JTextField();
        jSeparator35 = new javax.swing.JSeparator();
        btnActualizarTarea1 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnIngresarFuncionario = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnEditarFuncionario = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnEliminarFuncionario = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Drag = new javax.swing.JPanel();
        FrameDrag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.CardLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 693, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 19, -1, -1));

        btnSalir_Fun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CERRAR_MINI_ICON.png"))); // NOI18N
        btnSalir_Fun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalir_FunMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir_Fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(966, 15, -1, -1));

        btnAtras_Fun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ATRAS_MINI_ICON.png"))); // NOI18N
        btnAtras_Fun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtras_FunMouseClicked(evt);
            }
        });
        jPanel1.add(btnAtras_Fun, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 15, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("USER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 19, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/USER_MINI_ICON_MAINMENU.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 23, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSTRUCTORA VIALIS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 14, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CALENDARIO_MINI_ICON_MAINMENU.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 23, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 52, 978, 15));

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("jLabel6");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 23, -1, -1));

        jPanel9.setBackground(new java.awt.Color(102, 102, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel9.setLayout(new java.awt.CardLayout());

        PanelMenuActividades.setBackground(new java.awt.Color(102, 102, 255));
        PanelMenuActividades.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("¡Bienvenido al menú de Hitos y Actividades!");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Utiliza diversas herramientas para el control y gestión de los hitos de proyectos.");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HITOS_MENUPRINCIPAL.png"))); // NOI18N

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Funciones disponibles: ");

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("1.- Crear Nuevo Hito");

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("2.- Agregar Actividades a un Hito");

        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("3.- Control de Estados");

        javax.swing.GroupLayout PanelMenuActividadesLayout = new javax.swing.GroupLayout(PanelMenuActividades);
        PanelMenuActividades.setLayout(PanelMenuActividadesLayout);
        PanelMenuActividadesLayout.setHorizontalGroup(
            PanelMenuActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuActividadesLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(PanelMenuActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(PanelMenuActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(PanelMenuActividadesLayout.createSequentialGroup()
                            .addGroup(PanelMenuActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel54)
                                .addComponent(jLabel55)
                                .addComponent(jLabel56)
                                .addComponent(jLabel58))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11))
                        .addComponent(jLabel52)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        PanelMenuActividadesLayout.setVerticalGroup(
            PanelMenuActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuActividadesLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel52)
                .addGroup(PanelMenuActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuActividadesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel58))
                    .addGroup(PanelMenuActividadesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel11)))
                .addContainerGap(310, Short.MAX_VALUE))
        );

        jPanel9.add(PanelMenuActividades, "card7");

        PanelRegistrarHito.setBackground(new java.awt.Color(102, 102, 255));
        PanelRegistrarHito.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelRegistrarHito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Registro de Hito");
        PanelRegistrarHito.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Seleccione obra:");
        PanelRegistrarHito.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Nombre hito:");
        PanelRegistrarHito.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        txtNombreHito1.setBackground(new java.awt.Color(102, 102, 255));
        txtNombreHito1.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreHito1.setText("Ingrese hito...");
        txtNombreHito1.setBorder(null);
        txtNombreHito1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreHito1MouseClicked(evt);
            }
        });
        txtNombreHito1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreHito1KeyPressed(evt);
            }
        });
        PanelRegistrarHito.add(txtNombreHito1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 189, -1));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        PanelRegistrarHito.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 189, -1));

        btnRegistrarInspeccion1.setBackground(new java.awt.Color(0, 153, 153));
        btnRegistrarInspeccion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarInspeccion1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarInspeccion1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarInspeccion1MouseExited(evt);
            }
        });
        btnRegistrarInspeccion1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("REGISTRAR");
        btnRegistrarInspeccion1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, -1));

        PanelRegistrarHito.add(btnRegistrarInspeccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 150, 50));

        jScrollPane8.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane8.setBorder(null);
        jScrollPane8.setForeground(new java.awt.Color(255, 255, 255));

        tblSeleccionarObra_RegHito1.setBackground(new java.awt.Color(252, 251, 251));
        tblSeleccionarObra_RegHito1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSeleccionarObra_RegHito1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Puente Cau Cau"},
                {"Castillo Ratinbum"},
                {"Centro Pokémon"},
                {"Acuario de Jureles"}
            },
            new String [] {
                "NOMBRE DE OBRA"
            }
        ));
        tblSeleccionarObra_RegHito1.setGridColor(new java.awt.Color(255, 255, 255));
        tblSeleccionarObra_RegHito1.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSeleccionarObra_RegHito1.setShowHorizontalLines(false);
        tblSeleccionarObra_RegHito1.setShowVerticalLines(false);
        tblSeleccionarObra_RegHito1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccionarObra_RegHito1MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblSeleccionarObra_RegHito1);

        PanelRegistrarHito.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 640, 130));

        jPanel9.add(PanelRegistrarHito, "card2");

        PanelRegistrarActividades.setBackground(new java.awt.Color(102, 102, 255));
        PanelRegistrarActividades.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelRegistrarActividades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Registro de Tarea");
        PanelRegistrarActividades.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Seleccione hito:");
        PanelRegistrarActividades.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Nombre Tarea:");
        PanelRegistrarActividades.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, -1, -1));

        txtNombreTarea.setBackground(new java.awt.Color(102, 102, 255));
        txtNombreTarea.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreTarea.setText("Ingrese nombre...");
        txtNombreTarea.setBorder(null);
        txtNombreTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreTareaMouseClicked(evt);
            }
        });
        PanelRegistrarActividades.add(txtNombreTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 189, -1));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        PanelRegistrarActividades.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 189, -1));

        btnRegistrarTarea.setBackground(new java.awt.Color(0, 153, 153));
        btnRegistrarTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarTareaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarTareaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarTareaMouseExited(evt);
            }
        });
        btnRegistrarTarea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("REGISTRAR");
        btnRegistrarTarea.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, -1));

        PanelRegistrarActividades.add(btnRegistrarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 150, 50));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Fecha de Inicio:");
        PanelRegistrarActividades.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        txtFechaInicioTarea.setBackground(new java.awt.Color(102, 102, 255));
        txtFechaInicioTarea.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaInicioTarea.setText("DD/MM/AAAA");
        txtFechaInicioTarea.setBorder(null);
        txtFechaInicioTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaInicioTareaMouseClicked(evt);
            }
        });
        txtFechaInicioTarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaInicioTareaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaInicioTareaKeyReleased(evt);
            }
        });
        PanelRegistrarActividades.add(txtFechaInicioTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 189, -1));

        jSeparator31.setForeground(new java.awt.Color(255, 255, 255));
        PanelRegistrarActividades.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 189, -1));

        jLabel73.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Fecha de Termino:");
        PanelRegistrarActividades.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, -1, -1));

        txtFechaTerminoTarea.setBackground(new java.awt.Color(102, 102, 255));
        txtFechaTerminoTarea.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaTerminoTarea.setText("DD/MM/AAAA");
        txtFechaTerminoTarea.setBorder(null);
        txtFechaTerminoTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaTerminoTareaMouseClicked(evt);
            }
        });
        PanelRegistrarActividades.add(txtFechaTerminoTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 189, -1));

        jSeparator34.setForeground(new java.awt.Color(255, 255, 255));
        PanelRegistrarActividades.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 189, -1));

        jScrollPane10.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane10.setBorder(null);
        jScrollPane10.setForeground(new java.awt.Color(255, 255, 255));

        tblSeleccionarObra_Tarea.setBackground(new java.awt.Color(252, 251, 251));
        tblSeleccionarObra_Tarea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSeleccionarObra_Tarea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Puente Cau Cau"},
                {"Castillo Ratinbum"},
                {"Centro Pokémon"},
                {"Acuario de Jureles"}
            },
            new String [] {
                "NOMBRE DE OBRA"
            }
        ));
        tblSeleccionarObra_Tarea.setGridColor(new java.awt.Color(255, 255, 255));
        tblSeleccionarObra_Tarea.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSeleccionarObra_Tarea.setShowHorizontalLines(false);
        tblSeleccionarObra_Tarea.setShowVerticalLines(false);
        tblSeleccionarObra_Tarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccionarObra_TareaMouseClicked(evt);
            }
        });
        tblSeleccionarObra_Tarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblSeleccionarObra_TareaKeyReleased(evt);
            }
        });
        jScrollPane10.setViewportView(tblSeleccionarObra_Tarea);

        PanelRegistrarActividades.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 640, 130));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Seleccione obra:");
        PanelRegistrarActividades.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jScrollPane12.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane12.setBorder(null);
        jScrollPane12.setForeground(new java.awt.Color(255, 255, 255));

        tblSeleccioneHito_Tareas.setBackground(new java.awt.Color(252, 251, 251));
        tblSeleccioneHito_Tareas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSeleccioneHito_Tareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HITO", "ESTADO"
            }
        ));
        tblSeleccioneHito_Tareas.setGridColor(new java.awt.Color(255, 255, 255));
        tblSeleccioneHito_Tareas.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSeleccioneHito_Tareas.setShowHorizontalLines(false);
        tblSeleccioneHito_Tareas.setShowVerticalLines(false);
        tblSeleccioneHito_Tareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccioneHito_TareasMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(tblSeleccioneHito_Tareas);

        PanelRegistrarActividades.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 640, 130));

        jPanel9.add(PanelRegistrarActividades, "card2");

        PanelSeguimiento.setBackground(new java.awt.Color(102, 102, 255));
        PanelSeguimiento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelSeguimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Seguimiento de Hitos");
        PanelSeguimiento.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setBorder(null);
        jScrollPane6.setForeground(new java.awt.Color(255, 255, 255));

        tblSeleccionarObra_Seguimiento_Tareas.setBackground(new java.awt.Color(252, 251, 251));
        tblSeleccionarObra_Seguimiento_Tareas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSeleccionarObra_Seguimiento_Tareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Puente Cau Cau"},
                {"Castillo Ratinbum"},
                {"Centro Pokémon"},
                {"Acuario de Jureles"}
            },
            new String [] {
                "NOMBRE DE OBRA"
            }
        ));
        tblSeleccionarObra_Seguimiento_Tareas.setGridColor(new java.awt.Color(255, 255, 255));
        tblSeleccionarObra_Seguimiento_Tareas.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSeleccionarObra_Seguimiento_Tareas.setShowHorizontalLines(false);
        tblSeleccionarObra_Seguimiento_Tareas.setShowVerticalLines(false);
        tblSeleccionarObra_Seguimiento_Tareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccionarObra_Seguimiento_TareasMouseClicked(evt);
            }
        });
        tblSeleccionarObra_Seguimiento_Tareas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblSeleccionarObra_Seguimiento_TareasKeyReleased(evt);
            }
        });
        jScrollPane6.setViewportView(tblSeleccionarObra_Seguimiento_Tareas);

        PanelSeguimiento.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 350, 130));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Seleccione obra:");
        PanelSeguimiento.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane7.setBorder(null);
        jScrollPane7.setForeground(new java.awt.Color(255, 255, 255));

        tblSeleccioneTarea_Seguimiento.setBackground(new java.awt.Color(252, 251, 251));
        tblSeleccioneTarea_Seguimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSeleccioneTarea_Seguimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TAREA", "FECHA INICIO", "FECHA TERMINO", "PORCENTAJE"
            }
        ));
        tblSeleccioneTarea_Seguimiento.setGridColor(new java.awt.Color(255, 255, 255));
        tblSeleccioneTarea_Seguimiento.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSeleccioneTarea_Seguimiento.setShowHorizontalLines(false);
        tblSeleccioneTarea_Seguimiento.setShowVerticalLines(false);
        tblSeleccioneTarea_Seguimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccioneTarea_SeguimientoMouseClicked(evt);
            }
        });
        tblSeleccioneTarea_Seguimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblSeleccioneTarea_SeguimientoKeyReleased(evt);
            }
        });
        jScrollPane7.setViewportView(tblSeleccioneTarea_Seguimiento);

        PanelSeguimiento.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 880, 130));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Tarea seleccionada:");
        PanelSeguimiento.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jScrollPane11.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane11.setBorder(null);
        jScrollPane11.setForeground(new java.awt.Color(255, 255, 255));

        tblSeleccioneHito_Seguimiento.setBackground(new java.awt.Color(252, 251, 251));
        tblSeleccioneHito_Seguimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSeleccioneHito_Seguimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HITO", "ESTADO"
            }
        ));
        tblSeleccioneHito_Seguimiento.setGridColor(new java.awt.Color(255, 255, 255));
        tblSeleccioneHito_Seguimiento.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tblSeleccioneHito_Seguimiento.setShowHorizontalLines(false);
        tblSeleccioneHito_Seguimiento.setShowVerticalLines(false);
        tblSeleccioneHito_Seguimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccioneHito_SeguimientoMouseClicked(evt);
            }
        });
        tblSeleccioneHito_Seguimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblSeleccioneHito_SeguimientoKeyReleased(evt);
            }
        });
        jScrollPane11.setViewportView(tblSeleccioneHito_Seguimiento);

        PanelSeguimiento.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 500, 130));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Seleccione Hito:");
        PanelSeguimiento.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        txtTareaSeleccionada.setEditable(false);
        txtTareaSeleccionada.setBackground(new java.awt.Color(102, 102, 255));
        txtTareaSeleccionada.setForeground(new java.awt.Color(255, 255, 255));
        txtTareaSeleccionada.setText("Tarea Seleccionada...");
        PanelSeguimiento.add(txtTareaSeleccionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 220, 30));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Seleccione Tarea:");
        PanelSeguimiento.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel74.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Ingrese nuevo porcentaje:");
        PanelSeguimiento.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        txtPorcentajeAvance.setBackground(new java.awt.Color(102, 102, 255));
        txtPorcentajeAvance.setForeground(new java.awt.Color(255, 255, 255));
        txtPorcentajeAvance.setText("%");
        txtPorcentajeAvance.setBorder(null);
        txtPorcentajeAvance.setSelectionEnd(3);
        txtPorcentajeAvance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPorcentajeAvanceMouseClicked(evt);
            }
        });
        txtPorcentajeAvance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPorcentajeAvanceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPorcentajeAvanceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPorcentajeAvanceKeyTyped(evt);
            }
        });
        PanelSeguimiento.add(txtPorcentajeAvance, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 290, -1));

        jSeparator35.setForeground(new java.awt.Color(255, 255, 255));
        PanelSeguimiento.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 290, 10));

        btnActualizarTarea1.setBackground(new java.awt.Color(0, 153, 153));
        btnActualizarTarea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarTarea1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarTarea1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarTarea1MouseExited(evt);
            }
        });
        btnActualizarTarea1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("ACTUALIZAR");
        btnActualizarTarea1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, -1));

        PanelSeguimiento.add(btnActualizarTarea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 150, 50));

        jPanel9.add(PanelSeguimiento, "card4");

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 211, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresarFuncionario.setBackground(new java.awt.Color(255, 102, 0));
        btnIngresarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarFuncionarioMouseClicked(evt);
            }
        });
        btnIngresarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Crear Hito");
        btnIngresarFuncionario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HITOS_AGREGARHITO.png"))); // NOI18N
        btnIngresarFuncionario.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel3.add(btnIngresarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 130));

        btnEditarFuncionario.setBackground(new java.awt.Color(51, 0, 204));
        btnEditarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarFuncionarioMouseClicked(evt);
            }
        });
        btnEditarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Actividades ");
        btnEditarFuncionario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HITOS_AGREGARTAREA.png"))); // NOI18N
        btnEditarFuncionario.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, -1));

        jPanel3.add(btnEditarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 140, 130));

        btnEliminarFuncionario.setBackground(new java.awt.Color(204, 0, 204));
        btnEliminarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarFuncionarioMouseClicked(evt);
            }
        });
        btnEliminarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HITOS_SEGUIMIENTO.png"))); // NOI18N
        btnEliminarFuncionario.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 70));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Seguimiento");
        btnEliminarFuncionario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, -1));

        jPanel3.add(btnEliminarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 140, 130));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 74, -1, -1));

        Drag.setBackground(new java.awt.Color(102, 102, 255));

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FrameDragMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DragLayout = new javax.swing.GroupLayout(Drag);
        Drag.setLayout(DragLayout);
        DragLayout.setHorizontalGroup(
            DragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrameDrag, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        DragLayout.setVerticalGroup(
            DragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrameDrag, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(Drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void llenarObra(){
        try {
            Statement stmt = con.getConexion().createStatement();
            ResultSet rs = stmt.executeQuery("SELECT ID_PROY, NOMBRE_PROY FROM PROYECTO");
            DefaultTableModel value = new DefaultTableModel();
            tblSeleccionarObra_RegHito1.setModel(value);
            value.addColumn("NOMBRE DE OBRA");
            value.addColumn("ID_OBRA");
            tblSeleccionarObra_RegHito1.getColumnModel().getColumn(1).setMaxWidth(0);
            tblSeleccionarObra_RegHito1.getColumnModel().getColumn(1).setMinWidth(0);
            tblSeleccionarObra_RegHito1.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(0);
            tblSeleccionarObra_RegHito1.getTableHeader().getColumnModel().getColumn(1).setMinWidth(0);
            
            while(rs.next()){
                value.addRow(new Object[]{rs.getString("NOMBRE_PROY"),rs.getString("ID_PROY")});
            }
            rs.close();
        } catch (Exception e) {
            
        }
    }
    
    void llenarObraTarea(){
        try {
            Statement stmt = con.getConexion().createStatement();
            ResultSet rs = stmt.executeQuery("SELECT ID_PROY, NOMBRE_PROY FROM PROYECTO");
            DefaultTableModel value = new DefaultTableModel();
            tblSeleccionarObra_Tarea.setModel(value);
            value.addColumn("NOMBRE DE OBRA");
            value.addColumn("ID_OBRA");
            tblSeleccionarObra_Tarea.getColumnModel().getColumn(1).setMaxWidth(0);
            tblSeleccionarObra_Tarea.getColumnModel().getColumn(1).setMinWidth(0);
            tblSeleccionarObra_Tarea.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(0);
            tblSeleccionarObra_Tarea.getTableHeader().getColumnModel().getColumn(1).setMinWidth(0);
            while(rs.next()){
                value.addRow(new Object[]{rs.getString("NOMBRE_PROY"),rs.getString("ID_PROY")});
            }
            rs.close();
        } catch (Exception e) {
            
        }
    }
    
    void llenarHito(String proy_id){
        try {
            Statement stmt = con.getConexion().createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM HITO WHERE PROYECTO_ID_PROY = '"+proy_id+"'");
            DefaultTableModel value = new DefaultTableModel();
            tblSeleccioneHito_Tareas.setModel(value);
            value.addColumn("ID_HITO");
            value.addColumn("HITO");
            value.addColumn("PROYECTO_ID_PROY");
            value.addColumn("ESTADO");
            tblSeleccioneHito_Tareas.getColumnModel().getColumn(0).setMaxWidth(0);
            tblSeleccioneHito_Tareas.getColumnModel().getColumn(0).setMinWidth(0);
            tblSeleccioneHito_Tareas.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
            tblSeleccioneHito_Tareas.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
            tblSeleccioneHito_Tareas.getColumnModel().getColumn(2).setMaxWidth(0);
            tblSeleccioneHito_Tareas.getColumnModel().getColumn(2).setMinWidth(0);
            tblSeleccioneHito_Tareas.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(0);
            tblSeleccioneHito_Tareas.getTableHeader().getColumnModel().getColumn(2).setMinWidth(0);
            while(rs.next()){
                if(rs.getString("INSPECCION_AVANCE").equals("100%")){
                    value.addRow(new Object[]{rs.getString("ID_HITO"),rs.getString("NOMBRE_HITO"),rs.getString("PROYECTO_ID_PROY"),"Completo"});
                }else{
                    value.addRow(new Object[]{rs.getString("ID_HITO"),rs.getString("NOMBRE_HITO"),rs.getString("PROYECTO_ID_PROY"),"Incompleto"});
                }
            }
            rs.close();
        } catch (Exception e) {
            
        }
    }
    
    void llenarObraSeguimiento(){
        try {
            Statement stmt = con.getConexion().createStatement();
            ResultSet rs = stmt.executeQuery("SELECT ID_PROY, NOMBRE_PROY FROM PROYECTO");
            DefaultTableModel value = new DefaultTableModel();
            tblSeleccionarObra_Seguimiento_Tareas.setModel(value);
            value.addColumn("NOMBRE DE OBRA");
            value.addColumn("ID_OBRA");
            tblSeleccionarObra_Seguimiento_Tareas.getColumnModel().getColumn(1).setMaxWidth(0);
            tblSeleccionarObra_Seguimiento_Tareas.getColumnModel().getColumn(1).setMinWidth(0);
            tblSeleccionarObra_Seguimiento_Tareas.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(0);
            tblSeleccionarObra_Seguimiento_Tareas.getTableHeader().getColumnModel().getColumn(1).setMinWidth(0);
            
            while(rs.next()){
                value.addRow(new Object[]{rs.getString("NOMBRE_PROY"),rs.getString("ID_PROY")});
            }
            rs.close();
        } catch (Exception e) {
            
        }
    }
    
    void llenarHitoSeguimiento(String proy_id){
        try {
            Statement stmt = con.getConexion().createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM HITO WHERE PROYECTO_ID_PROY = '"+proy_id+"'");
            DefaultTableModel value = new DefaultTableModel();
            tblSeleccioneHito_Seguimiento.setModel(value);
            value.addColumn("ID_HITO");
            value.addColumn("HITO");
            value.addColumn("PROYECTO_ID_PROY");
            value.addColumn("ESTADO");
            tblSeleccioneHito_Seguimiento.getColumnModel().getColumn(0).setMaxWidth(0);
            tblSeleccioneHito_Seguimiento.getColumnModel().getColumn(0).setMinWidth(0);
            tblSeleccioneHito_Seguimiento.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
            tblSeleccioneHito_Seguimiento.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
            tblSeleccioneHito_Seguimiento.getColumnModel().getColumn(2).setMaxWidth(0);
            tblSeleccioneHito_Seguimiento.getColumnModel().getColumn(2).setMinWidth(0);
            tblSeleccioneHito_Seguimiento.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(0);
            tblSeleccioneHito_Seguimiento.getTableHeader().getColumnModel().getColumn(2).setMinWidth(0);
            while(rs.next()){
                if(rs.getString("INSPECCION_AVANCE").equals("100%")){
                    value.addRow(new Object[]{rs.getString("ID_HITO"),rs.getString("NOMBRE_HITO"),rs.getString("PROYECTO_ID_PROY"),"Completo"});
                }else{
                    value.addRow(new Object[]{rs.getString("ID_HITO"),rs.getString("NOMBRE_HITO"),rs.getString("PROYECTO_ID_PROY"),"Incompleto"});
                }
            }
            rs.close();
        } catch (Exception e) {
            
        }
    }
    
    void llenarTareaSeguimiento(String id_hito){
        try {
            Statement stmt = con.getConexion().createStatement();
            ResultSet rs = stmt.executeQuery("SELECT ID_TAR, NOMBRE_TAR , TO_CHAR(FECHA_INICIO_TAR,'DD/MM/YYYY') \"FECHA_INICIO_TAR\", TO_CHAR(FECHA_TERMINO_TAR,'DD/MM/YYYY') \"FECHA_TERMINO_TAR\", AVANCE_TAR FROM TAREA WHERE HITO_ID_HITO = '"+id_hito+"'");
            DefaultTableModel value = new DefaultTableModel();
            tblSeleccioneTarea_Seguimiento.setModel(value);
            value.addColumn("ID");
            value.addColumn("TAREA");
            value.addColumn("FECHA INICIO");
            value.addColumn("FECHA TERMINO");
            value.addColumn("PORCENTAJE");
            tblSeleccioneTarea_Seguimiento.getColumnModel().getColumn(0).setMaxWidth(0);
            tblSeleccioneTarea_Seguimiento.getColumnModel().getColumn(0).setMinWidth(0);
            tblSeleccioneTarea_Seguimiento.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
            tblSeleccioneTarea_Seguimiento.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
            
            while(rs.next()){
                value.addRow(new Object[]{rs.getString("ID_TAR"),rs.getString("NOMBRE_TAR"),rs.getString("FECHA_INICIO_TAR"),rs.getString("FECHA_TERMINO_TAR"),rs.getString("AVANCE_TAR")+"%"});
            }
            rs.close();
        } catch (Exception e) {
            
        }
    }
    
    private void btnSalir_FunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir_FunMouseClicked
        // TODO add your handling code here:
        new Mensajes_SalirAp().setVisible(true);
    }//GEN-LAST:event_btnSalir_FunMouseClicked

    private void btnAtras_FunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtras_FunMouseClicked
        // TODO add your handling code here:
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtras_FunMouseClicked

    private void tblSeleccionarObra_Seguimiento_TareasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccionarObra_Seguimiento_TareasMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)tblSeleccionarObra_Seguimiento_Tareas.getModel();
        String id_proy = String.valueOf(tm.getValueAt(tblSeleccionarObra_Seguimiento_Tareas.getSelectedRow(),1));
        llenarHitoSeguimiento(id_proy);
        txtTareaSeleccionada.setText("Tarea Seleccionada...");
        llenarTareaSeguimiento("");
    }//GEN-LAST:event_tblSeleccionarObra_Seguimiento_TareasMouseClicked

    private void tblSeleccioneTarea_SeguimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccioneTarea_SeguimientoMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)tblSeleccioneTarea_Seguimiento.getModel();
        String nombre_tarea = String.valueOf(tm.getValueAt(tblSeleccioneTarea_Seguimiento.getSelectedRow(),1));
        String avance = String.valueOf(tm.getValueAt(tblSeleccioneTarea_Seguimiento.getSelectedRow(),4));
        avance = avance.substring(0, avance.length()-1);
        txtTareaSeleccionada.setText(nombre_tarea);
        txtPorcentajeAvance.setText(avance);
    }//GEN-LAST:event_tblSeleccioneTarea_SeguimientoMouseClicked

    private void btnIngresarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarFuncionarioMouseClicked
        // TODO add your handling code here:

        btnIngresarFuncionario.setBackground(new Color (255,204,153));
        btnEditarFuncionario.setBackground(new Color (51,0,204));
        btnEliminarFuncionario.setBackground(new Color (204,0,204));


        PanelMenuActividades.setVisible(false);
        PanelRegistrarHito.setVisible(true);
        PanelRegistrarActividades.setVisible(false);
        PanelSeguimiento.setVisible(false);
        
        

    }//GEN-LAST:event_btnIngresarFuncionarioMouseClicked

    private void btnEditarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarFuncionarioMouseClicked
        // TODO add your handling code here:
        btnIngresarFuncionario.setBackground(new Color (255,102,0));
        btnEditarFuncionario.setBackground(new Color (204,204,255));
        btnEliminarFuncionario.setBackground(new Color (204,0,204));


        PanelMenuActividades.setVisible(false);
        PanelRegistrarHito.setVisible(false);
        PanelRegistrarActividades.setVisible(true);
        PanelSeguimiento.setVisible(false);
        

    }//GEN-LAST:event_btnEditarFuncionarioMouseClicked

    private void btnEliminarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarFuncionarioMouseClicked
        // TODO add your handling code here:
        btnIngresarFuncionario.setBackground(new Color (255,102,0));
        btnEditarFuncionario.setBackground(new Color (51,0,204));
        btnEliminarFuncionario.setBackground(new Color (255,153,255));


        PanelMenuActividades.setVisible(false);
        PanelRegistrarHito.setVisible(false);
        PanelRegistrarActividades.setVisible(false);
        PanelSeguimiento.setVisible(true);
        

    }//GEN-LAST:event_btnEliminarFuncionarioMouseClicked

    private void txtNombreHito1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreHito1MouseClicked
        // TODO add your handling code here:
        if(txtNombreHito1.getText().equals("Ingrese hito...")){
            txtNombreHito1.setText("");
        }
    }//GEN-LAST:event_txtNombreHito1MouseClicked

    private void btnRegistrarInspeccion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarInspeccion1MouseClicked
        // TODO add your handling code here:
        HitosConsultas hc = new HitosConsultas();
        String texto = txtNombreHito1.getText();
        texto = texto.replaceAll(" ", "");
        if(txtNombreHito1.getText().equals("Ingrese hito...") || texto.length()==0){
            JOptionPane.showMessageDialog(null, "Debe Ingresar Hito");
        }else if(tblSeleccionarObra_RegHito1.getSelectedColumn()!=0){
            JOptionPane.showMessageDialog(null, "Debe Seleccionar una Obra");
        }else{
            DefaultTableModel tm = (DefaultTableModel)tblSeleccionarObra_RegHito1.getModel();
            String id_proy = String.valueOf(tm.getValueAt(tblSeleccionarObra_RegHito1.getSelectedRow(),1));
            String nombre = txtNombreHito1.getText();
            hc.agregarHito(nombre, id_proy);
            txtNombreHito1.setText("Ingrese hito...");
            tblSeleccionarObra_RegHito1.clearSelection();
        }
    }//GEN-LAST:event_btnRegistrarInspeccion1MouseClicked

    private void btnRegistrarInspeccion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarInspeccion1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarInspeccion1MouseEntered

    private void btnRegistrarInspeccion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarInspeccion1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarInspeccion1MouseExited

    private void tblSeleccionarObra_RegHito1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccionarObra_RegHito1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSeleccionarObra_RegHito1MouseClicked

    private void txtNombreTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreTareaMouseClicked
        // TODO add your handling code here:
        txtNombreTarea.setText("");
    }//GEN-LAST:event_txtNombreTareaMouseClicked

    private void btnRegistrarTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarTareaMouseClicked
        // TODO add your handling code here:
        HitosConsultas hc = new HitosConsultas();
        String nombre_tarea = txtNombreTarea.getText();
        nombre_tarea = nombre_tarea.replaceAll(" ", "");
        
        if(tblSeleccionarObra_Tarea.getSelectedColumn()!=0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar una obra");
        }else if(tblSeleccioneHito_Tareas.getSelectedColumn()!=1){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un hito");
        }else if(txtNombreTarea.getText().equals("Ingrese nombre...") || nombre_tarea.length()==0){
            JOptionPane.showMessageDialog(null,"Debe ingresar un nombre de tarea" );
        }else if(txtFechaInicioTarea.getText().equals("DD/MM/AAAA")){
            JOptionPane.showMessageDialog(null, "Debe ingresar una fecha de inicio");
        }else if(txtFechaTerminoTarea.getText().equals("DD/MM/AAAA")){
            JOptionPane.showMessageDialog(null, "Debe ingresar una fecha de termino");
        }else{
        DefaultTableModel om = (DefaultTableModel)tblSeleccionarObra_Tarea.getModel();
        String id_proy = String.valueOf(om.getValueAt(tblSeleccionarObra_Tarea.getSelectedRow(),1));
        DefaultTableModel hm = (DefaultTableModel)tblSeleccioneHito_Tareas.getModel();
        String id_hito = String.valueOf(hm.getValueAt(tblSeleccioneHito_Tareas.getSelectedRow(),0));
        String nombre = txtNombreTarea.getText();
        String fecha_in = txtFechaInicioTarea.getText();
        String fecha_fin = txtFechaTerminoTarea.getText();
        hc.agregarTarea(nombre, fecha_in, fecha_fin, id_hito, id_proy);
        txtNombreTarea.setText("Ingrese nombre...");
        txtFechaInicioTarea.setText("DD/MM/AAAA");
        txtFechaTerminoTarea.setText("DD/MM/AAAA");
        tblSeleccionarObra_Tarea.clearSelection();
        llenarHito("");
        }
        
    }//GEN-LAST:event_btnRegistrarTareaMouseClicked

    private void btnRegistrarTareaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarTareaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarTareaMouseEntered

    private void btnRegistrarTareaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarTareaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarTareaMouseExited

    private void txtFechaInicioTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaInicioTareaMouseClicked
        // TODO add your handling code here:
        if(txtFechaInicioTarea.getText().equals("DD/MM/AAAA")){
            txtFechaInicioTarea.setText("");
        } 
    }//GEN-LAST:event_txtFechaInicioTareaMouseClicked

    private void txtFechaTerminoTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaTerminoTareaMouseClicked
        // TODO add your handling code here:
        txtFechaTerminoTarea.setText("");
    }//GEN-LAST:event_txtFechaTerminoTareaMouseClicked

    private void tblSeleccionarObra_TareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccionarObra_TareaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)tblSeleccionarObra_Tarea.getModel();
        String id_proy = String.valueOf(tm.getValueAt(tblSeleccionarObra_Tarea.getSelectedRow(),1));
        llenarHito(id_proy);
    }//GEN-LAST:event_tblSeleccionarObra_TareaMouseClicked

    private void tblSeleccioneHito_SeguimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccioneHito_SeguimientoMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)tblSeleccioneHito_Seguimiento.getModel();
        String id_hito = String.valueOf(tm.getValueAt(tblSeleccioneHito_Seguimiento.getSelectedRow(),0));
        llenarTareaSeguimiento(id_hito);
        txtTareaSeleccionada.setText("Tarea Seleccionada...");
    }//GEN-LAST:event_tblSeleccioneHito_SeguimientoMouseClicked

    private void txtPorcentajeAvanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPorcentajeAvanceMouseClicked
        // TODO add your handling code here:
        if(txtPorcentajeAvance.getText().equals("%")){
             txtPorcentajeAvance.setText("");
        }
       
    }//GEN-LAST:event_txtPorcentajeAvanceMouseClicked

    private void tblSeleccioneHito_TareasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccioneHito_TareasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSeleccioneHito_TareasMouseClicked

    private void txtNombreHito1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreHito1KeyPressed
        // TODO add your handling code here:
        if(txtNombreHito1.getText().equals("Ingrese hito...")){
            txtNombreHito1.setText("");
        }
    }//GEN-LAST:event_txtNombreHito1KeyPressed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        if(txtNombreHito1.getText().equals("")){
            txtNombreHito1.setText("Ingrese hito...");
        }
        if(txtNombreTarea.getText().equals("")){
            txtNombreTarea.setText("Ingrese nombre...");
        }
        if(txtFechaInicioTarea.getText().equals("")){
            txtFechaInicioTarea.setText("DD/MM/AAAA");
        }
        if(txtFechaTerminoTarea.getText().equals("")){
            txtFechaTerminoTarea.setText("DD/MM/AAAA");
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void tblSeleccioneHito_SeguimientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSeleccioneHito_SeguimientoKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)tblSeleccioneHito_Seguimiento.getModel();
        String id_hito = String.valueOf(tm.getValueAt(tblSeleccioneHito_Seguimiento.getSelectedRow(),0));
        llenarTareaSeguimiento(id_hito);
        txtTareaSeleccionada.setText("Tarea Seleccionada...");
    }//GEN-LAST:event_tblSeleccioneHito_SeguimientoKeyReleased

    private void tblSeleccionarObra_Seguimiento_TareasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSeleccionarObra_Seguimiento_TareasKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)tblSeleccionarObra_Seguimiento_Tareas.getModel();
        String id_proy = String.valueOf(tm.getValueAt(tblSeleccionarObra_Seguimiento_Tareas.getSelectedRow(),1));
        llenarHitoSeguimiento(id_proy);
        txtTareaSeleccionada.setText("Tarea Seleccionada...");
        llenarTareaSeguimiento("");
    }//GEN-LAST:event_tblSeleccionarObra_Seguimiento_TareasKeyReleased

    private void tblSeleccioneTarea_SeguimientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSeleccioneTarea_SeguimientoKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)tblSeleccioneTarea_Seguimiento.getModel();
        String nombre_tarea = String.valueOf(tm.getValueAt(tblSeleccioneTarea_Seguimiento.getSelectedRow(),1));
        String avance = String.valueOf(tm.getValueAt(tblSeleccioneTarea_Seguimiento.getSelectedRow(),4));
        avance = avance.substring(0, avance.length()-1);
        txtTareaSeleccionada.setText(nombre_tarea);
        txtPorcentajeAvance.setText(avance);
    }//GEN-LAST:event_tblSeleccioneTarea_SeguimientoKeyReleased

    private void tblSeleccionarObra_TareaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSeleccionarObra_TareaKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)tblSeleccionarObra_Tarea.getModel();
        String id_proy = String.valueOf(tm.getValueAt(tblSeleccionarObra_Tarea.getSelectedRow(),1));
        llenarHito(id_proy);
    }//GEN-LAST:event_tblSeleccionarObra_TareaKeyReleased

    private void txtPorcentajeAvanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentajeAvanceKeyPressed
        // TODO add your handling code here:
        if(txtPorcentajeAvance.getText().equals("%")){
          txtPorcentajeAvance.setText("");  
        } 
    }//GEN-LAST:event_txtPorcentajeAvanceKeyPressed

    private void txtPorcentajeAvanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentajeAvanceKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0' || c>'9'){
            evt.consume();
        }
        
    }//GEN-LAST:event_txtPorcentajeAvanceKeyTyped

    private void txtPorcentajeAvanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentajeAvanceKeyReleased
        // TODO add your handling code here:
        String cadena = txtPorcentajeAvance.getText();
        if(!cadena.equals("")){
            int porcentaje = Integer.parseInt(cadena);
            if(porcentaje >100){
                //JOptionPane.showMessageDialog(null, "Debe ser menor a 100");
                cadena = cadena.substring(0, cadena.length()-1);
                txtPorcentajeAvance.setText(cadena); 
            } 
        }
        
    }//GEN-LAST:event_txtPorcentajeAvanceKeyReleased

    private void txtFechaInicioTareaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaInicioTareaKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtFechaInicioTareaKeyReleased

    private void txtFechaInicioTareaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaInicioTareaKeyPressed
        // TODO add your handling code here:
        if(txtFechaInicioTarea.getText().equals("DD/MM/AAAA")){
            txtFechaInicioTarea.setText("");
        }
    }//GEN-LAST:event_txtFechaInicioTareaKeyPressed

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen(); //para rescatar el valor X de la posición de la ventana
        int y = evt.getYOnScreen(); //para rescatar el valor Y de la posición de la ventana

        this.setLocation(x - xMouse ,y - yMouse);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FrameDragMouseClicked

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FrameDragMousePressed

    private void btnActualizarTarea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTarea1MouseClicked
        // TODO add your handling code here:
       DefaultTableModel tm = (DefaultTableModel)tblSeleccioneHito_Seguimiento.getModel();
       String id_hito = String.valueOf(tm.getValueAt(tblSeleccioneHito_Seguimiento.getSelectedRow(),0));
       DefaultTableModel tm1 = (DefaultTableModel)tblSeleccioneTarea_Seguimiento.getModel();
       String id_tarea = String.valueOf(tm1.getValueAt(tblSeleccioneTarea_Seguimiento.getSelectedRow(),0));
       int avance = Integer.parseInt(txtPorcentajeAvance.getText());
       HitosConsultas hc = new HitosConsultas();
       
       if(txtPorcentajeAvance.getText().equals("%") || txtPorcentajeAvance.getText().equals("")|| id_hito.equals("")||id_tarea.equals("")){
           JOptionPane.showMessageDialog(null, "Debe seleccionar elementos.");
       }else{
           hc.actualizarTarea(id_tarea, id_hito, String.valueOf(avance));
       }
    }//GEN-LAST:event_btnActualizarTarea1MouseClicked

    private void btnActualizarTarea1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTarea1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTarea1MouseEntered

    private void btnActualizarTarea1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTarea1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTarea1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Hitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Hitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Hitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Hitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Hitos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Drag;
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JPanel PanelMenuActividades;
    private javax.swing.JPanel PanelRegistrarActividades;
    private javax.swing.JPanel PanelRegistrarHito;
    private javax.swing.JPanel PanelSeguimiento;
    private javax.swing.JPanel btnActualizarTarea1;
    private javax.swing.JLabel btnAtras_Fun;
    private javax.swing.JPanel btnEditarFuncionario;
    private javax.swing.JPanel btnEliminarFuncionario;
    private javax.swing.JPanel btnIngresarFuncionario;
    private javax.swing.JPanel btnRegistrarInspeccion1;
    private javax.swing.JPanel btnRegistrarTarea;
    private javax.swing.JLabel btnSalir_Fun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTable tblSeleccionarObra_RegHito1;
    private javax.swing.JTable tblSeleccionarObra_Seguimiento_Tareas;
    private javax.swing.JTable tblSeleccionarObra_Tarea;
    private javax.swing.JTable tblSeleccioneHito_Seguimiento;
    private javax.swing.JTable tblSeleccioneHito_Tareas;
    private javax.swing.JTable tblSeleccioneTarea_Seguimiento;
    private javax.swing.JTextField txtFechaInicioTarea;
    private javax.swing.JTextField txtFechaTerminoTarea;
    private javax.swing.JTextField txtNombreHito1;
    private javax.swing.JTextField txtNombreTarea;
    private javax.swing.JTextField txtPorcentajeAvance;
    private javax.swing.JTextField txtTareaSeleccionada;
    // End of variables declaration//GEN-END:variables
}
